#!/usr/bin/env python3
"""Exact source-only equal-half carrier map for the frozen HX448C02 R1CS.

The artifact generated by this module is intentionally compact.  It defines a
total, invertible map for every canonical sparse A/B/C entry and an exact row
schedule, but it never materializes the 67,108,864-row matrices.  No proof
backend, compiler, or production verifier is invoked.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any, Iterable, Iterator, Sequence


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
UPSTREAM = ROOT / ".agent/hardening/hvzk-whir-odd-field-r1cs"
MANIFEST_PATH = HERE / "carrier_manifest.json"
CERTIFICATE_PATH = HERE / "certificate.json"
TEST_PATH = HERE / "test_compiler.py"

P = 0xFFFFFFFF00000001
FIELD_BYTES = 8
PROFILE = "blake2b448-mixed"
SOURCE_M = 20_457_227
SOURCE_N = 19_311_555
SOURCE_L = 10_152
SOURCE_WITNESS = SOURCE_N - SOURCE_L
SOURCE_NNZ = 94_551_238
PRIVATE_TRANSPORT = 77_376
DERIVED_AUXILIARY = 19_224_027
ELL = 1 << 25
N0 = ELL
CARRIER_SIDE = 2 * ELL
PUBLIC_WITH_CONSTANT = SOURCE_L + 1
PUBLIC_PADDING = ELL - PUBLIC_WITH_CONSTANT
WITNESS_PADDING = ELL - SOURCE_WITNESS
WITNESS_ZERO_ROW_START = SOURCE_M
WITNESS_ZERO_ROW_END = SOURCE_M + WITNESS_PADDING
ZERO_ROW_PADDING = CARRIER_SIDE - WITNESS_ZERO_ROW_END
EMBEDDED_NNZ = SOURCE_NNZ + 2 * WITNESS_PADDING
LOG_ELL = 25
SUMCHECK_VARIABLES = LOG_ELL + 1
INNER_MASK_ORACLES = 3 * SUMCHECK_VARIABLES
OUTER_MASK_ORACLES = SUMCHECK_VARIABLES
WITNESS_ORACLES = 1
TOTAL_ENCODED_ORACLES = WITNESS_ORACLES + INNER_MASK_ORACLES + OUTER_MASK_ORACLES

RELATION_DIGEST = (
    "81f88eb0afd355bbd50d90d0760b65e341b4b490a29af3d5e0a8acf1721e4279"
    "2bd547fd62559263f1c70edf365fb482fde2f88117c3ae98b2360934a3c75254"
)
UPSTREAM_SOURCE_SET_DIGEST = (
    "968bfcf34da1caf9fed1c81581a225dffb0e7ba160c5ed1cda5900dfe59f3286e"
    "877f7646da91089050c788338f29a40db65b73dc5ccbf95280ff0173ee2575a"
)

UPSTREAM_PINS: dict[str, tuple[int, str, str]] = {
    "compiler.py": (
        107_386,
        "62bd836c41fac8691e2ff97414c33d3bb955ae2b5cb833721e811e3e52b43c179"
        "3676a98178007fc3727bad825545cd8075d06b44c467d4d54b6a3cdf70226b5",
        "frozen macro-R1CS compiler and source contract checker",
    ),
    "test_compiler.py": (
        7_327,
        "e5e4eb4a5b2b3ff8f54160d5f498e7908b4166f14e867eeff5710c0b958643a4"
        "f0961718792a7efe8bdfeba7524d77fe04bb08c5dfc1a9c2ccdf0aa6e98e0069",
        "frozen macro-R1CS dependency-free tests",
    ),
    "relation_manifest.json": (
        102_003,
        "dae278e46a5d2ed2c58fae4443db8b73967f2b1190336520081a6f3791c04fad6"
        "3d182cc61c0e1fb75f66bdb70e9ff40d4b1b975d9295fcf3a93bf189c76607e",
        "canonical frozen macro-R1CS relation manifest",
    ),
    "certificate.json": (
        4_337,
        "f6b2cdc6944a55c013d5d89644579ac8e10cb20cac7e74e5887b8230c735e3b8d"
        "4adea09a130fe35e8eb0327ba99ec8ac27e119b764c3995a15d2b16375e4bfd",
        "canonical frozen macro-R1CS source certificate",
    ),
}

MATRIX_ORDER = {"A": 0, "B": 1, "C": 2}
CANONICAL_RULE = (
    "UTF-8, recursively sorted keys, separators ',' and ':', no insignificant "
    "whitespace, exactly one trailing LF; duplicate JSON keys reject"
)


def canonical_bytes(value: Any) -> bytes:
    return (json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + "\n").encode()


def sha512_bytes(data: bytes) -> str:
    return hashlib.sha512(data).hexdigest()


def sha512_file(path: Path) -> str:
    return sha512_bytes(path.read_bytes())


def shake_digest(domain: bytes, payload: bytes) -> str:
    return hashlib.shake_256(domain + len(payload).to_bytes(8, "big") + payload).hexdigest(64)


def reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def parse_canonical_json_bytes(raw: bytes, *, max_bytes: int) -> Any:
    if not isinstance(raw, bytes):
        raise TypeError("parser accepts immutable bytes only")
    if not raw or len(raw) > max_bytes:
        raise ValueError("JSON byte length outside exact parser bound")
    try:
        text = raw.decode("utf-8", "strict")
        value = json.loads(text, object_pairs_hook=reject_duplicate_keys)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError("invalid canonical JSON") from exc
    if canonical_bytes(value) != raw:
        raise ValueError("noncanonical JSON bytes")
    return value


def parse_canonical_json_file(path: Path, *, exact_bytes: int) -> Any:
    raw = path.read_bytes()
    if len(raw) != exact_bytes:
        raise ValueError(f"unexpected byte length for {path}")
    return parse_canonical_json_bytes(raw, max_bytes=exact_bytes)


def encode_coefficient(value: int) -> str:
    if not isinstance(value, int) or isinstance(value, bool) or not (0 < value < P):
        raise ValueError("sparse coefficient must be canonical and nonzero")
    return value.to_bytes(FIELD_BYTES, "little").hex()


def decode_coefficient(encoded: str) -> int:
    if not isinstance(encoded, str) or len(encoded) != 2 * FIELD_BYTES:
        raise ValueError("coefficient must be exactly eight encoded bytes")
    if encoded.lower() != encoded or any(ch not in "0123456789abcdef" for ch in encoded):
        raise ValueError("coefficient must be lowercase hexadecimal")
    value = int.from_bytes(bytes.fromhex(encoded), "little")
    if not (0 < value < P):
        raise ValueError("zero or noncanonical coefficient")
    return value


@dataclass(frozen=True, order=True)
class SparseEntry:
    """One nonzero in A, B, or C.

    Ordering is supplied separately because the paper/source convention is
    row, then A/B/C, then strictly increasing column.
    """

    matrix: str
    row: int
    column: int
    coefficient: int

    def as_json(self) -> dict[str, Any]:
        return {
            "coefficient_le_hex": encode_coefficient(self.coefficient),
            "column": self.column,
            "matrix": self.matrix,
            "row": self.row,
        }


def entry_key(entry: SparseEntry) -> tuple[int, int, int]:
    if entry.matrix not in MATRIX_ORDER:
        raise ValueError("matrix must be A, B, or C")
    return entry.row, MATRIX_ORDER[entry.matrix], entry.column


@dataclass(frozen=True)
class CarrierSpec:
    source_m: int = SOURCE_M
    source_n: int = SOURCE_N
    source_l: int = SOURCE_L
    source_nnz: int = SOURCE_NNZ
    ell: int = ELL

    @property
    def witness_used(self) -> int:
        return self.source_n - self.source_l

    @property
    def side(self) -> int:
        return 2 * self.ell

    @property
    def public_padding(self) -> int:
        return self.ell - (self.source_l + 1)

    @property
    def witness_padding(self) -> int:
        return self.ell - self.witness_used

    @property
    def witness_zero_end(self) -> int:
        return self.source_m + self.witness_padding

    @property
    def zero_rows(self) -> int:
        return self.side - self.witness_zero_end

    def validate(self) -> None:
        if self.source_l < 0 or self.source_m < 0 or self.source_n < self.source_l:
            raise ValueError("invalid source geometry")
        if self.ell <= 0 or self.ell & (self.ell - 1):
            raise ValueError("ell must be a positive power of two")
        if self.source_l + 1 > self.ell or self.witness_used > self.ell:
            raise ValueError("source does not fit equal halves")
        if self.witness_zero_end > self.side:
            raise ValueError("padding constraints do not fit square carrier")
        if self.source_nnz < 0:
            raise ValueError("negative source nonzero count")


PRODUCTION_SPEC = CarrierSpec()


def next_power_of_two(value: int) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
        raise ValueError("power-of-two input must be positive integer")
    return 1 << (value - 1).bit_length()


def derive_equal_half_spec(*, m: int, n: int, l: int, nnz: int) -> CarrierSpec:
    """Derive the smallest power-of-two half for this exact padding schedule.

    Besides fitting the public and witness halves, `ell >= m-(n-l)` is needed
    because every unused witness coordinate consumes one row after all source
    rows.  This is stronger and more directly tied to the chosen schedule than
    merely requiring `2*ell >= m`.
    """
    for name, value in (("m", m), ("n", n), ("l", l), ("nnz", nnz)):
        if not isinstance(value, int) or isinstance(value, bool):
            raise ValueError(f"{name} must be an integer")
    if m < 0 or n < 0 or l < 0 or nnz < 0 or l > n:
        raise ValueError("invalid parameterized source geometry")
    witness = n - l
    lower_bound = max(1, l + 1, witness, m - witness)
    spec = CarrierSpec(source_m=m, source_n=n, source_l=l, source_nnz=nnz, ell=next_power_of_two(lower_bound))
    spec.validate()
    return spec


def validate_relation_digest(digest: str) -> str:
    if (
        not isinstance(digest, str)
        or len(digest) != 128
        or digest.lower() != digest
        or any(ch not in "0123456789abcdef" for ch in digest)
    ):
        raise ValueError("source relation digest must be canonical 64-byte lowercase hex")
    if int(digest, 16) == 0:
        raise ValueError("source relation digest must be nonzero")
    return digest


def parameterized_projection(*, m: int, n: int, l: int, nnz: int, source_relation_digest: str) -> dict[str, Any]:
    """Return a non-authoritative map descriptor for an exact future relation.

    This output is intentionally not retained or authorized.  A future W64 or
    HX512 relation must supply its new digest and geometry, then independently
    pin its source/compiler/refinement evidence.
    """
    spec = derive_equal_half_spec(m=m, n=n, l=l, nnz=nnz)
    digest = validate_relation_digest(source_relation_digest)
    mapping = mapping_descriptor(spec)
    projection = {
        "artifact_schema": "hegemon.cfw26.section11.carrier-map.parameterized-projection.v1",
        "authority": {
            "authoritative_section11_carrier": False,
            "production_authorized": False,
            "semantic_refinement_proved": False,
            "source_pins_verified": False,
        },
        "carrier": {
            "ell": spec.ell,
            "matrix_nonzeros_total": spec.source_nnz + 2 * spec.witness_padding,
            "n0": spec.ell,
            "remaining_zero_rows": spec.zero_rows,
            "side": spec.side,
            "witness_zero_rows": spec.witness_padding,
        },
        "mapping": mapping,
        "source": {
            "l": spec.source_l,
            "m": spec.source_m,
            "n": spec.source_n,
            "nnz": spec.source_nnz,
            "relation_digest_shake256_512": digest,
        },
        "status": "parameterized arithmetic projection only; rerun source pins refinement theorem security and production gates",
    }
    projection["projection_digest_shake256_512"] = shake_digest(
        b"hegemon.cfw26.section11.carrier-map.parameterized-projection.v1\0",
        canonical_bytes(projection),
    )
    return projection


def map_source_column(column: int, spec: CarrierSpec = PRODUCTION_SPEC) -> int:
    spec.validate()
    if not isinstance(column, int) or isinstance(column, bool) or not (0 <= column <= spec.source_n):
        raise ValueError("source column outside z")
    if column <= spec.source_l:
        return column
    return spec.ell + column - (spec.source_l + 1)


def unmap_source_column(column: int, spec: CarrierSpec = PRODUCTION_SPEC) -> int:
    spec.validate()
    if not isinstance(column, int) or isinstance(column, bool):
        raise ValueError("embedded column must be an integer")
    if 0 <= column <= spec.source_l:
        return column
    witness_end = spec.ell + spec.witness_used
    if spec.ell <= column < witness_end:
        return spec.source_l + 1 + column - spec.ell
    raise ValueError("embedded column is padding or outside source image")


def validate_source_entry(entry: SparseEntry, spec: CarrierSpec = PRODUCTION_SPEC) -> None:
    if entry.matrix not in MATRIX_ORDER:
        raise ValueError("invalid source matrix")
    if not (0 <= entry.row < spec.source_m):
        raise ValueError("source row outside source relation")
    map_source_column(entry.column, spec)
    encode_coefficient(entry.coefficient)


def map_source_entry(entry: SparseEntry, spec: CarrierSpec = PRODUCTION_SPEC) -> SparseEntry:
    validate_source_entry(entry, spec)
    return replace(entry, column=map_source_column(entry.column, spec))


def unmap_source_entry(entry: SparseEntry, spec: CarrierSpec = PRODUCTION_SPEC) -> SparseEntry:
    if entry.matrix not in MATRIX_ORDER or not (0 <= entry.row < spec.source_m):
        raise ValueError("entry is not in mapped source row image")
    encode_coefficient(entry.coefficient)
    source = replace(entry, column=unmap_source_column(entry.column, spec))
    validate_source_entry(source, spec)
    return source


def validate_mapped_pair(source: SparseEntry, mapped: SparseEntry, spec: CarrierSpec = PRODUCTION_SPEC) -> None:
    if map_source_entry(source, spec) != mapped:
        raise ValueError("mapped entry is not the exact source image")
    if unmap_source_entry(mapped, spec) != source:
        raise ValueError("mapped entry does not invert exactly")


def witness_padding_entries(index: int, spec: CarrierSpec = PRODUCTION_SPEC) -> tuple[SparseEntry, SparseEntry]:
    """Return the exact A and B nonzeros for padding equation x*1=0."""
    spec.validate()
    if not isinstance(index, int) or isinstance(index, bool) or not (0 <= index < spec.witness_padding):
        raise ValueError("witness-padding index outside schedule")
    row = spec.source_m + index
    x_column = spec.ell + spec.witness_used + index
    return SparseEntry("A", row, x_column, 1), SparseEntry("B", row, 0, 1)


def validate_padding_entry_pair(
    index: int, entries: Sequence[SparseEntry], spec: CarrierSpec = PRODUCTION_SPEC
) -> None:
    expected = witness_padding_entries(index, spec)
    if tuple(entries) != expected:
        raise ValueError("padding row must be exactly A[x]=1, B[v0]=1, C empty")


def source_stream_to_carrier(
    entries: Iterable[SparseEntry], spec: CarrierSpec = PRODUCTION_SPEC
) -> Iterator[SparseEntry]:
    """Stream source entries without buffering or changing stream identity."""
    previous: tuple[int, int, int] | None = None
    count = 0
    for entry in entries:
        key = entry_key(entry)
        if previous is not None and key <= previous:
            raise ValueError("source sparse stream is duplicated or noncanonical")
        mapped = map_source_entry(entry, spec)
        validate_mapped_pair(entry, mapped, spec)
        yield mapped
        previous = key
        count += 1
    if count != spec.source_nnz:
        raise ValueError("source sparse stream has a missing or extra nonzero")


def carrier_padding_stream(spec: CarrierSpec = PRODUCTION_SPEC) -> Iterator[SparseEntry]:
    for index in range(spec.witness_padding):
        yield from witness_padding_entries(index, spec)


def validate_public_half(values: Sequence[int], spec: CarrierSpec = PRODUCTION_SPEC) -> None:
    if len(values) != spec.ell or values[0] != 1:
        raise ValueError("public half must have ell elements and v[0]=1")
    if any(value != 0 for value in values[spec.source_l + 1 :]):
        raise ValueError("public parser padding must be exactly zero")


def validate_witness_padding(values: Sequence[int], spec: CarrierSpec = PRODUCTION_SPEC) -> None:
    if len(values) != spec.ell:
        raise ValueError("witness half must have ell elements")
    if any(value % P != 0 for value in values[spec.witness_used :]):
        raise ValueError("existential witness padding violates x*1=0")


def embed_source_assignment(source_z: Sequence[int], spec: CarrierSpec = PRODUCTION_SPEC) -> list[int]:
    spec.validate()
    if len(source_z) != spec.source_n + 1 or source_z[0] != 1:
        raise ValueError("source assignment length or constant slot mismatch")
    if any(not isinstance(value, int) or isinstance(value, bool) or not (0 <= value < P) for value in source_z):
        raise ValueError("source assignment contains noncanonical field element")
    v = list(source_z[: spec.source_l + 1]) + [0] * spec.public_padding
    w = list(source_z[spec.source_l + 1 :]) + [0] * spec.witness_padding
    validate_public_half(v, spec)
    validate_witness_padding(w, spec)
    return v + w


def eval_linear(entries: Iterable[SparseEntry], assignment: Sequence[int]) -> int:
    return sum(entry.coefficient * assignment[entry.column] for entry in entries) % P


def row_values(entries: Iterable[SparseEntry], assignment: Sequence[int], row: int) -> tuple[int, int, int]:
    lanes: dict[str, list[SparseEntry]] = {"A": [], "B": [], "C": []}
    for entry in entries:
        if entry.row == row:
            lanes[entry.matrix].append(entry)
    return tuple(eval_linear(lanes[matrix], assignment) for matrix in ("A", "B", "C"))


def row_holds(values: tuple[int, int, int]) -> bool:
    a, b, c = values
    return a * b % P == c


def fixture_payload() -> dict[str, Any]:
    spec = CarrierSpec(source_m=3, source_n=5, source_l=2, source_nnz=8, ell=4)
    entries = [
        SparseEntry("A", 0, 1, 1),
        SparseEntry("B", 0, 3, 1),
        SparseEntry("C", 0, 4, 1),
        SparseEntry("A", 1, 5, 1),
        SparseEntry("B", 1, 0, 1),
        SparseEntry("A", 2, 1, 1),
        SparseEntry("A", 2, 2, P - 1),
        SparseEntry("B", 2, 0, 1),
    ]
    return {
        "entries": [entry.as_json() for entry in entries],
        "field_modulus_decimal": str(P),
        "geometry": {
            "ell": spec.ell,
            "matrix_nonzeros_total": spec.source_nnz,
            "m_constraints": spec.source_m,
            "n_nonconstant_variables": spec.source_n,
            "public_variables": spec.source_l,
        },
        "schema": "hegemon.cfw26.section11.carrier-map.tiny-r1cs.v1",
    }


def fixture_bytes(payload: dict[str, Any] | None = None) -> bytes:
    body = fixture_payload() if payload is None else payload
    digest = shake_digest(b"hegemon.cfw26.section11.carrier-map.tiny-r1cs.v1\0", canonical_bytes(body))
    return canonical_bytes({**body, "relation_digest_shake256_512": digest})


def parse_fixture(raw: bytes) -> tuple[CarrierSpec, list[SparseEntry]]:
    value = parse_canonical_json_bytes(raw, max_bytes=16_384)
    expected_keys = {
        "entries",
        "field_modulus_decimal",
        "geometry",
        "relation_digest_shake256_512",
        "schema",
    }
    if not isinstance(value, dict) or set(value) != expected_keys:
        raise ValueError("tiny fixture top-level schema mismatch")
    if value["schema"] != "hegemon.cfw26.section11.carrier-map.tiny-r1cs.v1":
        raise ValueError("tiny fixture schema mismatch")
    if value["field_modulus_decimal"] != str(P):
        raise ValueError("tiny fixture field mismatch")
    body = {key: value[key] for key in value if key != "relation_digest_shake256_512"}
    digest = shake_digest(b"hegemon.cfw26.section11.carrier-map.tiny-r1cs.v1\0", canonical_bytes(body))
    if value["relation_digest_shake256_512"] != digest:
        raise ValueError("tiny fixture relation digest mismatch")
    geometry = value["geometry"]
    if not isinstance(geometry, dict) or set(geometry) != {
        "ell",
        "matrix_nonzeros_total",
        "m_constraints",
        "n_nonconstant_variables",
        "public_variables",
    }:
        raise ValueError("tiny fixture geometry schema mismatch")
    if any(not isinstance(geometry[key], int) or isinstance(geometry[key], bool) for key in geometry):
        raise ValueError("tiny fixture geometry type mismatch")
    spec = CarrierSpec(
        source_m=geometry["m_constraints"],
        source_n=geometry["n_nonconstant_variables"],
        source_l=geometry["public_variables"],
        source_nnz=geometry["matrix_nonzeros_total"],
        ell=geometry["ell"],
    )
    spec.validate()
    raw_entries = value["entries"]
    if not isinstance(raw_entries, list) or len(raw_entries) != spec.source_nnz:
        raise ValueError("tiny fixture missing or extra nnz")
    entries: list[SparseEntry] = []
    previous: tuple[int, int, int] | None = None
    for item in raw_entries:
        if not isinstance(item, dict) or set(item) != {"coefficient_le_hex", "column", "matrix", "row"}:
            raise ValueError("tiny fixture entry schema mismatch")
        if not isinstance(item["row"], int) or isinstance(item["row"], bool):
            raise ValueError("tiny fixture row type mismatch")
        if not isinstance(item["column"], int) or isinstance(item["column"], bool):
            raise ValueError("tiny fixture column type mismatch")
        entry = SparseEntry(item["matrix"], item["row"], item["column"], decode_coefficient(item["coefficient_le_hex"]))
        validate_source_entry(entry, spec)
        key = entry_key(entry)
        if previous is not None and key <= previous:
            raise ValueError("tiny fixture duplicate or noncanonical sparse entry")
        previous = key
        entries.append(entry)
    return spec, entries


def check_fixture_parity() -> dict[str, Any]:
    spec, source_entries = parse_fixture(fixture_bytes())
    source_z = [1, 3, 3, 4, 12, 0]
    carrier_z = embed_source_assignment(source_z, spec)
    mapped = [map_source_entry(entry, spec) for entry in source_entries]
    for row in range(spec.source_m):
        source_values = row_values(source_entries, source_z, row)
        embedded_values = row_values(mapped, carrier_z, row)
        if source_values != embedded_values or not row_holds(source_values):
            raise AssertionError((row, source_values, embedded_values))
    padding = list(witness_padding_entries(0, spec))
    if not row_holds(row_values(padding, carrier_z, spec.source_m)):
        raise AssertionError("tiny witness padding row")
    if spec.zero_rows != 4:
        raise AssertionError("tiny zero row count")
    for row in range(spec.witness_zero_end, spec.side):
        empty_values = row_values((), carrier_z, row)
        if empty_values != (0, 0, 0) or not row_holds(empty_values):
            raise AssertionError(("tiny empty row", row, empty_values))
    return {
        "carrier_side": spec.side,
        "mapped_source_nonzeros": len(mapped),
        "source_rows": spec.source_m,
        "witness_zero_rows": spec.witness_padding,
        "zero_rows": spec.zero_rows,
    }


def source_file_entries() -> list[dict[str, Any]]:
    files = {
        HERE / "compiler.py": "equal-half sparse-map compiler and checker",
        TEST_PATH: "dependency-free mutation and parity tests",
    }
    result: list[dict[str, Any]] = []
    for path, role in sorted(files.items(), key=lambda item: item[0].as_posix()):
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"local source must be a regular non-symlink file: {path}")
        raw = path.read_bytes()
        result.append(
            {
                "bytes": len(raw),
                "path": path.relative_to(ROOT).as_posix(),
                "role": role,
                "sha512": sha512_bytes(raw),
            }
        )
    for name, (size, digest, role) in sorted(UPSTREAM_PINS.items()):
        result.append(
            {
                "bytes": size,
                "path": (UPSTREAM / name).relative_to(ROOT).as_posix(),
                "role": role,
                "sha512": digest,
            }
        )
    return sorted(result, key=lambda item: item["path"])


def source_set_digest(entries: list[dict[str, Any]]) -> str:
    h = hashlib.sha512(b"hegemon.cfw26.section11.carrier-map.source-set.v1\0")
    for entry in entries:
        path = entry["path"].encode()
        role = entry["role"].encode()
        h.update(len(path).to_bytes(4, "big"))
        h.update(path)
        h.update(entry["bytes"].to_bytes(8, "big"))
        h.update(bytes.fromhex(entry["sha512"]))
        h.update(len(role).to_bytes(4, "big"))
        h.update(role)
    return h.hexdigest()


def load_upstream() -> tuple[dict[str, Any], dict[str, Any]]:
    snapshots: dict[str, bytes] = {}
    for name, (size, digest, _role) in UPSTREAM_PINS.items():
        path = UPSTREAM / name
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"frozen upstream source must be a regular non-symlink file: {name}")
        raw = path.read_bytes()
        if len(raw) != size or sha512_bytes(raw) != digest:
            raise ValueError(f"frozen upstream source pin drift: {name}")
        snapshots[name] = raw
    manifest = parse_canonical_json_bytes(snapshots["relation_manifest.json"], max_bytes=102_003)
    certificate = parse_canonical_json_bytes(snapshots["certificate.json"], max_bytes=4_337)
    validate_upstream(manifest, certificate)
    return manifest, certificate


def validate_upstream(manifest: dict[str, Any], certificate: dict[str, Any]) -> None:
    if manifest.get("artifact_schema") != "hegemon.hx448c02.odd-field-r1cs.relation-manifest.v1":
        raise ValueError("upstream manifest schema drift")
    if certificate.get("artifact_schema") != "hegemon.hx448c02.odd-field-r1cs.certificate.v1":
        raise ValueError("upstream certificate schema drift")
    if manifest.get("source_set_digest_sha512") != UPSTREAM_SOURCE_SET_DIGEST:
        raise ValueError("upstream source-set digest drift")
    if certificate.get("source_set_digest_sha512") != UPSTREAM_SOURCE_SET_DIGEST:
        raise ValueError("upstream certificate source-set drift")
    relation_raw = canonical_bytes(manifest)
    actual_relation_digest = shake_digest(
        b"hegemon.hx448c02.odd-field-r1cs.relation-manifest.v1\0", relation_raw
    )
    if actual_relation_digest != RELATION_DIGEST or certificate.get("relation_manifest_digest_shake256_512") != RELATION_DIGEST:
        raise ValueError("upstream relation identity drift")
    expected_geometry = {
        "auxiliary_variables_total": SOURCE_WITNESS,
        "derived_auxiliary_variables": DERIVED_AUXILIARY,
        "l_public_variables": SOURCE_L,
        "m_constraints": SOURCE_M,
        "matrix_nonzeros_total": SOURCE_NNZ,
        "n_nonconstant_variables": SOURCE_N,
        "private_transport_variables": PRIVATE_TRANSPORT,
        "z_vector_length_including_constant_one": SOURCE_N + 1,
    }
    profile = manifest.get("hash_profiles", {}).get(PROFILE, {})
    if profile.get("geometry") != expected_geometry:
        raise ValueError("upstream mixed-profile geometry drift")
    candidate = profile.get("cfw26_section11_candidate_embedding", {})
    if (
        candidate.get("ell") != ELL
        or candidate.get("n0") != N0
        or candidate.get("authoritative_cfw26_theorem_binding") is not False
        or candidate.get("embedded_geometry", {}).get("rows") != CARRIER_SIDE
        or candidate.get("embedded_geometry", {}).get("matrix_nonzeros_total") != EMBEDDED_NNZ
        or candidate.get("padding", {}).get("public_parser_zero_elements") != PUBLIC_PADDING
        or candidate.get("padding", {}).get("witness_zero_elements_and_rows") != WITNESS_PADDING
        or candidate.get("padding", {}).get("row_zero_padding") != ZERO_ROW_PADDING
    ):
        raise ValueError("upstream candidate padding arithmetic drift")
    if any(manifest.get("authority", {}).values()):
        raise ValueError("upstream source-only authority became true")
    boundary = manifest.get("source_stage_boundary", {})
    if (
        boundary.get("expanded_matrix_retained") is not False
        or boundary.get("formal_scalar_to_r1cs_refinement") is not False
        or boundary.get("proof_built_or_measured") is not False
    ):
        raise ValueError("upstream stage boundary drift")
    if manifest.get("host_only_boundary", {}).get("compiled_rows") != 0:
        raise ValueError("upstream host-only boundary unexpectedly changed")
    false_certificate_fields = (
        "complete_zero_knowledge_proved",
        "composed_qrom_pq128_proved",
        "exact_native_verifier_refinement_proved",
        "expanded_matrix_retained",
        "full_production_relation_compiled",
        "host_only_boundary_closed",
        "proof_built",
        "production_authorized",
    )
    if any(certificate.get(field) is not False for field in false_certificate_fields):
        raise ValueError("upstream certificate authority drift")


def mapping_descriptor(spec: CarrierSpec = PRODUCTION_SPEC) -> dict[str, Any]:
    spec.validate()
    descriptor = {
        "coefficient_map": "identity in canonical Goldilocks encoding; zero coefficients remain absent",
        "entry_identity": "(matrix in A,B,C,row,source_column,coefficient); stream order row,A/B/C,column",
        "inverse": {
            "embedded_0_through_l": "source column is unchanged",
            "embedded_ell_through_ell_plus_witness_used_minus_1": "source column = l+1+(embedded-ell)",
            "padding_columns": "not in source-entry image and inverse rejects",
        },
        "matrix_map": "A->A, B->B, C->C",
        "row_map": "source row r maps to carrier row r",
        "segments": [
            {
                "count": 1,
                "embedded_columns": [0, 1],
                "kind": "constant",
                "rule": "c -> c",
                "source_columns": [0, 1],
            },
            {
                "count": spec.source_l,
                "embedded_columns": [1, spec.source_l + 1],
                "kind": "public",
                "rule": "c -> c",
                "source_columns": [1, spec.source_l + 1],
            },
            {
                "count": spec.witness_used,
                "embedded_columns": [spec.ell, spec.ell + spec.witness_used],
                "kind": "witness_and_derived_auxiliary",
                "rule": "c -> ell+c-(l+1)",
                "source_columns": [spec.source_l + 1, spec.source_n + 1],
            },
        ],
        "source_entry_count": spec.source_nnz,
        "mapped_source_entry_count": spec.source_nnz,
        "universal_bijection_scope": (
            "every canonical nonzero entry of every source A/B/C sparse stream with the supplied geometry; "
            f"the compact frozen source artifact does not retain the {spec.source_nnz:,}-coordinate expanded stream"
        ),
        "universal_bijection_argument": (
            "the constant/public identity intervals and witness translation interval partition every source column, "
            "their images are disjoint with equal cardinalities, the displayed inverse is two-sided on those images, "
            "and matrix row coefficient plus stream ordinal are identities"
        ),
    }
    descriptor["descriptor_digest_shake256_512"] = shake_digest(
        b"hegemon.cfw26.section11.carrier-map.descriptor.v1\0", canonical_bytes(descriptor)
    )
    return descriptor


def build_manifest() -> dict[str, Any]:
    load_upstream()
    sources = source_file_entries()
    spec = PRODUCTION_SPEC
    spec.validate()
    if TOTAL_ENCODED_ORACLES != 4 * LOG_ELL + 5:
        raise AssertionError("Section 11 oracle ledger")
    return {
        "artifact": "CFW26 Section 11 equal-half carrier sparse-map certificate for frozen HX448C02 mixed R1CS",
        "artifact_schema": "hegemon.cfw26.section11.carrier-map.v1",
        "authority": {
            "authoritative_section11_carrier": False,
            "complete_zero_knowledge_proved": False,
            "composed_qrom_pq128_proved": False,
            "exact_native_verifier_refinement_proved": False,
            "full_hegemon_semantic_refinement_proved": False,
            "full_production_relation_compiled": False,
            "paper_completeness_as_printed": False,
            "paper_theorem_instantiated": False,
            "parser_padding_binding_proved": False,
            "pcs_mapping_defined": False,
            "production_authorized": False,
            "source_macro_to_expanded_matrix_refinement_proved": False,
        },
        "canonical_json": CANONICAL_RULE,
        "carrier": {
            "column_count": spec.side,
            "ell": spec.ell,
            "field_modulus_decimal": str(P),
            "matrix_shape": [spec.side, spec.side],
            "n0": spec.ell,
            "nonconstant_variables": spec.side - 1,
            "row_count": spec.side,
            "z_flattening": "v[0..ell) || w[0..ell)",
        },
        "cfw26_printed_source_defects": {
            "coefficient_branch_selected": False,
            "mask_factor": {
                "construction_first_equation_coefficient": 1,
                "decomposition_and_hvzk_value_claim_coefficient": 2,
                "printed_equations_consistent": False,
                "repair_branch_theorem_proved": False,
            },
            "main_typed_form": {
                "candidate_required_row": "row_M(M,alpha)[b] = Mhat(alpha,b,1)",
                "candidate_state_must_include_alpha": True,
                "printed_state_typechecks": False,
                "repair_refinement_or_theorem_proved": False,
            },
            "paper_pdf_sha512": (
                "be9595b264ccbb6e5d848a10e24f907089ff478c7efe99967a5d0f236bffcaf87"
                "c53cc82eec53f74856a08a4db8a6884084c8238291f44d06aa2d703eef5c2dd"
            ),
            "st2": {
                "candidate_repair": "pow(1)=(1,1,...)",
                "counterexample_coefficients_low_to_high": [0, str(P - 1), 1],
                "counterexample_polynomial": "s(X)=X^2-X",
                "counterexample_s_at_0": 0,
                "counterexample_s_at_1": 0,
                "printed_definition": "st2=(0,1,0,...)",
                "printed_dot_coefficients": str(P - 1),
                "printed_endpoint_test_correct": False,
                "repaired_pow1_dot_coefficients": 0,
            },
            "status": "printed completeness and theorem authority remain false; repairs are candidates only",
        },
        "exact_padding": {
            "public_half": {
                "constant_interval": [0, 1],
                "parser_fixed_zero_interval": [spec.source_l + 1, spec.ell],
                "parser_fixed_zero_elements": spec.public_padding,
                "public_interval": [1, spec.source_l + 1],
                "zero_constraint_rows": 0,
            },
            "row_layout": [
                {"interval": [0, spec.source_m], "kind": "source_rows", "rows": spec.source_m},
                {
                    "equation": "w[used+i] * v[0] = 0",
                    "interval": [spec.source_m, spec.witness_zero_end],
                    "kind": "witness_zero_rows",
                    "matrix_nonzeros_per_row": {"A": 1, "B": 1, "C": 0},
                    "rows": spec.witness_padding,
                },
                {
                    "equation": "0*0=0",
                    "interval": [spec.witness_zero_end, spec.side],
                    "kind": "canonical_empty_rows",
                    "rows": spec.zero_rows,
                },
            ],
            "witness_half": {
                "derived_auxiliary_interval": [PRIVATE_TRANSPORT, spec.witness_used],
                "private_transport_interval": [0, PRIVATE_TRANSPORT],
                "zero_interval": [spec.witness_used, spec.ell],
                "zero_rows": spec.witness_padding,
            },
        },
        "geometry": {
            "carrier_matrix_nonzeros_total": EMBEDDED_NNZ,
            "mapped_source_nonzeros": SOURCE_NNZ,
            "public_zero_padding": PUBLIC_PADDING,
            "remaining_zero_rows": ZERO_ROW_PADDING,
            "source_constraints": SOURCE_M,
            "source_nonconstant_variables": SOURCE_N,
            "source_public_variables": SOURCE_L,
            "source_witness_variables": SOURCE_WITNESS,
            "witness_zero_padding_elements_rows": WITNESS_PADDING,
            "witness_zero_padding_nonzeros": 2 * WITNESS_PADDING,
        },
        "refinement_boundary": {
            "closed_source_only_properties": [
                "strict canonical parsing and exact upstream source hashes",
                "total injective column map with an exact inverse on its image",
                "matrix lane row coefficient and stream identity preservation",
                "disjoint exhaustive constant public and witness source-column segments",
                "explicit witness-padding x*1=0 entries and canonical remaining empty rows",
                "tiny exact row-evaluation parity and fail-closed mutation fixtures",
            ],
            "expanded_matrices_retained": False,
            "parameterized_projection_available": True,
            "retained_certificate_stale_on_source_relation_digest_change": True,
            "open_release_blockers": [
                "upstream macro schedule to exact expanded sparse-coordinate refinement",
                "canonical production parser to v public-padding refinement",
                "full Hegemon scalar semantics to this carrier",
                "resolution and proof of the printed Section 11 st2 coefficient and typed-form defects",
                "complete adaptive zero knowledge and whole Fiat-Shamir view simulation",
                "PCS IOP RBR grinding and deployed-hash QROM composition at at least 128 bits",
                "exact Rust verifier consensus and lifecycle refinement",
                "retained proof construction mutation restart artifact and measured bytes",
            ],
            "verdict": "EXACT_SPARSE_MAP_DEFINED_SOURCE_ONLY_ALL_SECURITY_AND_PRODUCTION_AUTHORITY_FAIL_CLOSED",
        },
        "section11_encoded_oracles": {
            "codeword_lengths": None,
            "hybrid_count_4_log2_ell_plus_5": 4 * LOG_ELL + 5,
            "inner_mask_oracles_3_times_log2_ell_plus_1": INNER_MASK_ORACLES,
            "log2_ell": LOG_ELL,
            "outer_mask_oracles_log2_ell_plus_1": OUTER_MASK_ORACLES,
            "pcs_mapping_defined": False,
            "proof_bytes": None,
            "query_schedule": None,
            "sumcheck_boolean_variables_log2_2ell": SUMCHECK_VARIABLES,
            "total_encoded_oracles": TOTAL_ENCODED_ORACLES,
            "witness_oracles": WITNESS_ORACLES,
        },
        "source_relation": {
            "profile": PROFILE,
            "relation_manifest_digest_shake256_512": RELATION_DIGEST,
            "source_set_digest_sha512": UPSTREAM_SOURCE_SET_DIGEST,
            "status": "frozen HX448C02 host-only negative baseline; not the future all-W64 manifest/HX512 successor",
        },
        "sources": sources,
        "sources_digest_sha512": source_set_digest(sources),
        "sparse_mapping": mapping_descriptor(spec),
        "tests_required": [
            "strict upstream hashes canonical JSON and frozen relation digest",
            "closed-form segment coverage disjointness endpoint and inverse checks",
            "tiny fixture source-to-carrier evaluation parity",
            "index-shift constant-slot public-padding witness-padding row-map matrix-lane and coefficient mutations",
            "duplicate and missing sparse nnz plus relation-digest mutations",
            "printed st2 endpoint counterexample and candidate pow(1) arithmetic",
            "all authority flags remain false and all 105 encoded oracles are counted without PCS claims",
        ],
    }


def build_certificate(manifest: dict[str, Any]) -> dict[str, Any]:
    raw = canonical_bytes(manifest)
    return {
        "artifact_schema": "hegemon.cfw26.section11.carrier-map.certificate.v1",
        "authority": manifest["authority"],
        "canonical_manifest_bytes": len(raw),
        "canonical_manifest_rule": CANONICAL_RULE,
        "carrier_geometry": manifest["geometry"],
        "carrier_manifest_digest_shake256_512": shake_digest(
            b"hegemon.cfw26.section11.carrier-map.manifest.v1\0", raw
        ),
        "carrier_manifest_file": MANIFEST_PATH.name,
        "mapping_descriptor_digest_shake256_512": manifest["sparse_mapping"]["descriptor_digest_shake256_512"],
        "measured_proof_bytes": None,
        "proof_artifact_retained": False,
        "section11_encoded_oracles": manifest["section11_encoded_oracles"],
        "source_relation_digest_shake256_512": RELATION_DIGEST,
        "stale_on_source_relation_digest_change": True,
        "sources_digest_sha512": manifest["sources_digest_sha512"],
        "tests_required": manifest["tests_required"],
        "verdict": manifest["refinement_boundary"]["verdict"],
    }


def check_closed_form_bijection(spec: CarrierSpec = PRODUCTION_SPEC) -> dict[str, Any]:
    spec.validate()
    boundaries = [0, 1, spec.source_l, spec.source_l + 1, spec.source_n]
    for column in boundaries:
        mapped = map_source_column(column, spec)
        if unmap_source_column(mapped, spec) != column:
            raise AssertionError((column, mapped))
    source_segment_count = 1 + spec.source_l + spec.witness_used
    if source_segment_count != spec.source_n + 1:
        raise AssertionError("source column segment partition")
    public_image = (0, spec.source_l + 1)
    witness_image = (spec.ell, spec.ell + spec.witness_used)
    if public_image[1] > witness_image[0] or witness_image[1] > spec.side:
        raise AssertionError("mapped column segments overlap or overflow")
    for padding_column in (spec.source_l + 1, spec.ell - 1, spec.ell + spec.witness_used, spec.side - 1):
        try:
            unmap_source_column(padding_column, spec)
        except ValueError:
            pass
        else:
            raise AssertionError(("padding inverse accepted", padding_column))
    embedded_nnz = spec.source_nnz + 2 * spec.witness_padding
    if spec is PRODUCTION_SPEC and embedded_nnz != EMBEDDED_NNZ:
        raise AssertionError("frozen embedded nnz equation")
    return {
        "carrier_side": spec.side,
        "column_domain": spec.source_n + 1,
        "mapped_source_nnz": spec.source_nnz,
        "padding_nnz": 2 * spec.witness_padding,
    }


def expect_reject(name: str, fn: Any) -> str:
    try:
        fn()
    except (AssertionError, TypeError, ValueError):
        return name
    raise AssertionError(f"mutation accepted: {name}")


def check_mutations() -> list[str]:
    spec, entries = parse_fixture(fixture_bytes())
    source = entries[0]
    mapped = map_source_entry(source, spec)
    rejected: list[str] = []
    rejected.append(expect_reject("index_shift", lambda: validate_mapped_pair(source, replace(mapped, column=mapped.column + 1), spec)))
    padding = witness_padding_entries(0, spec)
    rejected.append(
        expect_reject(
            "constant_slot",
            lambda: validate_padding_entry_pair(0, (padding[0], replace(padding[1], column=1)), spec),
        )
    )
    good_assignment = embed_source_assignment([1, 3, 3, 4, 12, 0], spec)
    bad_public = list(good_assignment[: spec.ell])
    bad_public[spec.source_l + 1] = 1
    rejected.append(expect_reject("public_padding", lambda: validate_public_half(bad_public, spec)))
    bad_witness = list(good_assignment[spec.ell :])
    bad_witness[spec.witness_used] = 1
    rejected.append(expect_reject("witness_padding", lambda: validate_witness_padding(bad_witness, spec)))
    rejected.append(expect_reject("row_mapping", lambda: validate_mapped_pair(source, replace(mapped, row=mapped.row + 1), spec)))
    rejected.append(expect_reject("matrix_lane", lambda: validate_mapped_pair(source, replace(mapped, matrix="B"), spec)))
    rejected.append(
        expect_reject(
            "coefficient",
            lambda: validate_mapped_pair(source, replace(mapped, coefficient=2), spec),
        )
    )

    body = fixture_payload()
    duplicate = json.loads(json.dumps(body))
    duplicate["entries"].insert(1, duplicate["entries"][0])
    duplicate["geometry"]["matrix_nonzeros_total"] += 1
    rejected.append(expect_reject("duplicate_nnz", lambda: parse_fixture(fixture_bytes(duplicate))))
    missing = json.loads(json.dumps(body))
    missing["entries"].pop()
    rejected.append(expect_reject("missing_nnz", lambda: parse_fixture(fixture_bytes(missing))))
    digest_mutation = json.loads(fixture_bytes())
    digest_mutation["relation_digest_shake256_512"] = "00" * 64
    rejected.append(expect_reject("relation_digest", lambda: parse_fixture(canonical_bytes(digest_mutation))))
    shifted = json.loads(json.dumps(body))
    shifted["entries"][0]["column"] = shifted["geometry"]["n_nonconstant_variables"] + 1
    rejected.append(expect_reject("noncanonical_or_duplicate_shift", lambda: parse_fixture(fixture_bytes(shifted))))
    unknown = json.loads(json.dumps(body))
    unknown["unexpected"] = 1
    rejected.append(expect_reject("unknown_field", lambda: parse_fixture(fixture_bytes(unknown))))
    rejected.append(expect_reject("noncanonical_json", lambda: parse_fixture(fixture_bytes()[:-1] + b" \n")))
    return rejected


def check_st2_counterexample() -> dict[str, int]:
    coefficients = [0, P - 1, 1]
    s0 = coefficients[0] % P
    s1 = sum(coefficients) % P
    printed_st2 = coefficients[1] % P
    repaired_pow1 = sum(coefficients) % P
    if (s0, s1, printed_st2, repaired_pow1) != (0, 0, P - 1, 0):
        raise AssertionError("st2 counterexample arithmetic")
    return {"printed_dot": printed_st2, "repaired_pow1_dot": repaired_pow1, "s_at_0": s0, "s_at_1": s1}


def emit() -> None:
    manifest = build_manifest()
    certificate = build_certificate(manifest)
    MANIFEST_PATH.write_bytes(canonical_bytes(manifest))
    CERTIFICATE_PATH.write_bytes(canonical_bytes(certificate))


def verify_artifacts(verbose: bool = True) -> dict[str, Any]:
    manifest = build_manifest()
    certificate = build_certificate(manifest)
    expected_manifest = canonical_bytes(manifest)
    expected_certificate = canonical_bytes(certificate)
    if not MANIFEST_PATH.exists() or MANIFEST_PATH.read_bytes() != expected_manifest:
        raise AssertionError("carrier_manifest.json missing or stale; run emit")
    if not CERTIFICATE_PATH.exists() or CERTIFICATE_PATH.read_bytes() != expected_certificate:
        raise AssertionError("certificate.json missing or stale; run emit")
    parsed_manifest = parse_canonical_json_file(MANIFEST_PATH, exact_bytes=len(expected_manifest))
    parsed_certificate = parse_canonical_json_file(CERTIFICATE_PATH, exact_bytes=len(expected_certificate))
    if parsed_manifest != manifest or parsed_certificate != certificate:
        raise AssertionError("canonical artifact parse mismatch")
    if any(manifest["authority"].values()) or any(certificate["authority"].values()):
        raise AssertionError("authority flag became true")
    if manifest["section11_encoded_oracles"]["total_encoded_oracles"] != 105:
        raise AssertionError("encoded oracle count drift")
    bijection = check_closed_form_bijection()
    fixture = check_fixture_parity()
    mutations = check_mutations()
    st2 = check_st2_counterexample()
    result = {
        "bijection": bijection,
        "carrier_manifest_digest_shake256_512": certificate["carrier_manifest_digest_shake256_512"],
        "fixture": fixture,
        "mutations_rejected": mutations,
        "section11_encoded_oracles": 105,
        "st2_counterexample": st2,
        "verdict": certificate["verdict"],
    }
    if verbose:
        print(json.dumps(result, sort_keys=True))
    return result


def summary() -> None:
    result = verify_artifacts(verbose=False)
    payload = {
        "artifact_sha512": {
            "carrier_manifest.json": sha512_file(MANIFEST_PATH),
            "certificate.json": sha512_file(CERTIFICATE_PATH),
            "compiler.py": sha512_file(HERE / "compiler.py"),
            "test_compiler.py": sha512_file(TEST_PATH),
        },
        "carrier_manifest_digest_shake256_512": result["carrier_manifest_digest_shake256_512"],
        "geometry": build_manifest()["geometry"],
        "section11_encoded_oracles": 105,
        "sources_digest_sha512": build_manifest()["sources_digest_sha512"],
        "verdict": result["verdict"],
    }
    print(json.dumps(payload, sort_keys=True))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in ("emit", "check", "summary"):
        subparsers.add_parser(command)
    project = subparsers.add_parser("project")
    project.add_argument("--m", type=int, required=True)
    project.add_argument("--n", type=int, required=True)
    project.add_argument("--l", type=int, required=True)
    project.add_argument("--nnz", type=int, required=True)
    project.add_argument("--source-relation-digest", required=True)
    args = parser.parse_args(argv)
    if args.command == "emit":
        emit()
    elif args.command == "check":
        verify_artifacts()
    elif args.command == "summary":
        summary()
    else:
        print(
            json.dumps(
                parameterized_projection(
                    m=args.m,
                    n=args.n,
                    l=args.l,
                    nnz=args.nnz,
                    source_relation_digest=args.source_relation_digest,
                ),
                sort_keys=True,
            )
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
