import HegemonCrypto.CmsOracleSimulation
import Mathlib.Data.Fin.Tuple.Basic

/-!
# Oracle-to-database bridge for the CMS compressed oracle

This module formalizes the finite counting and Cauchy--Schwarz core of Zhandry's
oracle-to-database lemma (How to Record Quantum Queries, Lemma 5).  For `k` claimed
oracle input/output pairs, the Fourier indices omitted by the measured-database event
are exactly those with a zero coordinate.  There are at most

`k * |Y|^(k - 1)`

such indices out of `|Y|^k`.  Consequently their total squared amplitude is at most
`k / |Y|` for a subnormalized state.

The proof below is finite and exact.  It does not assume a classical query log or a
cryptographic property of the random oracle.
-/

namespace HegemonCrypto.CmsOracleDatabaseBridge

open scoped BigOperators
open HegemonCrypto.CmsCompressedOracle
open HegemonCrypto.CmsKernelBounds
open HegemonCrypto.CmsLocalOperator
open HegemonCrypto.CmsCompressedOracleUnitary
open HegemonCrypto.CmsOracleSimulation

noncomputable section

set_option linter.unusedSectionVars false
set_option maxHeartbeats 800000

variable {Output Context : Type*}
variable [Fintype Output] [DecidableEq Output]
variable [Fintype Context] [DecidableEq Context]

/-- Fourier tuples with at least one zero coordinate. -/
def zeroCoordinateIndices
    (arity : Nat)
    (zero : Output) :
    Finset (Fin arity → Output) :=
  Finset.univ.filter fun index => ∃ coordinate, index coordinate = zero

/-- Insert a zero at the witnessed coordinate of an otherwise arbitrary tuple. -/
def insertZeroWitness
    {remaining : Nat}
    (zero : Output)
    (witness : Fin (remaining + 1) × (Fin remaining → Output)) :
    Fin (remaining + 1) → Output :=
  witness.1.insertNth zero witness.2

@[simp]
theorem insert_zero_witness_at_selected
    {remaining : Nat}
    (zero : Output)
    (witness : Fin (remaining + 1) × (Fin remaining → Output)) :
    insertZeroWitness zero witness witness.1 = zero := by
  simp [insertZeroWitness]

/--
Every tuple with a zero coordinate is generated by selecting one such coordinate and
removing it.  This is the finite surjection behind the union bound.
-/
theorem zero_coordinate_indices_subset_image
    (remaining : Nat)
    (zero : Output) :
    zeroCoordinateIndices (remaining + 1) zero ⊆
      (Finset.univ :
        Finset (Fin (remaining + 1) × (Fin remaining → Output))).image
          (insertZeroWitness zero) := by
  intro index indexBad
  simp only [zeroCoordinateIndices, Finset.mem_filter, Finset.mem_univ,
    true_and] at indexBad
  obtain ⟨coordinate, coordinateZero⟩ := indexBad
  let witness : Fin (remaining + 1) × (Fin remaining → Output) :=
    (coordinate, coordinate.removeNth index)
  have restores :
      insertZeroWitness zero witness = index := by
    unfold insertZeroWitness witness
    rw [← coordinateZero]
    exact coordinate.insertNth_self_removeNth index
  rw [← restores]
  exact Finset.mem_image_of_mem _ (Finset.mem_univ witness)

/--
Exact cardinality envelope used in the multi-output form of Zhandry Lemma 5.
-/
theorem zero_coordinate_indices_card_le
    (remaining : Nat)
    (zero : Output) :
    (zeroCoordinateIndices (remaining + 1) zero).card ≤
      (remaining + 1) * Fintype.card Output ^ remaining := by
  calc
    (zeroCoordinateIndices (remaining + 1) zero).card ≤
        ((Finset.univ :
          Finset (Fin (remaining + 1) × (Fin remaining → Output))).image
            (insertZeroWitness zero)).card :=
      Finset.card_le_card
        (zero_coordinate_indices_subset_image remaining zero)
    _ ≤
        (Finset.univ :
          Finset (Fin (remaining + 1) × (Fin remaining → Output))).card :=
      Finset.card_image_le
    _ = (remaining + 1) * Fintype.card Output ^ remaining := by
      simp

/--
The finite Fourier/Cauchy--Schwarz heart of the oracle-to-database bridge.

`coefficient context index` is the normalized final-state coefficient denoted
`alpha` in the published proof.  The result bounds the squared norm contributed by
indices with at least one zero coordinate.
-/
theorem zero_coordinate_fourier_mass_le
    (remaining : Nat)
    (zero : Output)
    (normalization : ℂ)
    (normalizationNorm :
      Complex.normSq normalization =
        1 / (Fintype.card Output : ℝ) ^ (remaining + 1))
    (coefficient : Context → (Fin (remaining + 1) → Output) → ℂ)
    (subnormalized :
      (∑ context : Context,
        ∑ index : Fin (remaining + 1) → Output,
          Complex.normSq (coefficient context index)) ≤ 1) :
    (∑ context : Context,
      Complex.normSq
        (normalization *
          ∑ index ∈ zeroCoordinateIndices (remaining + 1) zero,
            coefficient context index)) ≤
      (remaining + 1 : ℝ) / Fintype.card Output := by
  letI : Nonempty Output := ⟨zero⟩
  let bad := zeroCoordinateIndices (remaining + 1) zero
  have outputPositive : (0 : ℝ) < Fintype.card Output := by
    exact_mod_cast Fintype.card_pos (α := Output)
  have pointwise :
      ∀ context : Context,
        Complex.normSq
            (normalization *
              ∑ index ∈ bad, coefficient context index) ≤
          (bad.card : ℝ) /
              (Fintype.card Output : ℝ) ^ (remaining + 1) *
            ∑ index ∈ bad, Complex.normSq (coefficient context index) := by
    intro context
    rw [Complex.normSq_mul, normalizationNorm]
    have cauchy :=
      normSq_sum_le_card_mul_sum_normSq bad
        (fun index => coefficient context index)
    calc
      (1 / (Fintype.card Output : ℝ) ^ (remaining + 1)) *
          Complex.normSq (∑ index ∈ bad, coefficient context index) ≤
        (1 / (Fintype.card Output : ℝ) ^ (remaining + 1)) *
          ((bad.card : ℝ) *
            ∑ index ∈ bad, Complex.normSq (coefficient context index)) := by
          exact mul_le_mul_of_nonneg_left cauchy (by positivity)
      _ =
        (bad.card : ℝ) /
            (Fintype.card Output : ℝ) ^ (remaining + 1) *
          ∑ index ∈ bad, Complex.normSq (coefficient context index) := by
          ring
  calc
    (∑ context : Context,
      Complex.normSq
        (normalization *
          ∑ index ∈ zeroCoordinateIndices (remaining + 1) zero,
            coefficient context index)) ≤
        ∑ context : Context,
          ((bad.card : ℝ) /
              (Fintype.card Output : ℝ) ^ (remaining + 1)) *
            ∑ index ∈ bad,
              Complex.normSq (coefficient context index) := by
      simpa [bad] using Finset.sum_le_sum fun context _ => pointwise context
    _ =
        ((bad.card : ℝ) /
            (Fintype.card Output : ℝ) ^ (remaining + 1)) *
          ∑ context : Context,
            ∑ index ∈ bad,
              Complex.normSq (coefficient context index) := by
      rw [Finset.mul_sum]
    _ ≤
        ((bad.card : ℝ) /
            (Fintype.card Output : ℝ) ^ (remaining + 1)) * 1 := by
      apply mul_le_mul_of_nonneg_left
      · calc
          (∑ context : Context,
            ∑ index ∈ bad,
              Complex.normSq (coefficient context index)) ≤
              ∑ context : Context,
                ∑ index : Fin (remaining + 1) → Output,
                  Complex.normSq (coefficient context index) := by
            apply Finset.sum_le_sum
            intro context _
            exact Finset.sum_le_univ_sum_of_nonneg
              (fun index => Complex.normSq_nonneg (coefficient context index))
          _ ≤ 1 := subnormalized
      · positivity
    _ ≤ (remaining + 1 : ℝ) / Fintype.card Output := by
      rw [mul_one]
      have cardBound :=
        zero_coordinate_indices_card_le
          (Output := Output) remaining zero
      have cardBoundReal :
          (bad.card : ℝ) ≤
            (remaining + 1 : ℝ) *
              (Fintype.card Output : ℝ) ^ remaining := by
        exact_mod_cast cardBound
      calc
        (bad.card : ℝ) /
            (Fintype.card Output : ℝ) ^ (remaining + 1) ≤
          ((remaining + 1 : ℝ) *
              (Fintype.card Output : ℝ) ^ remaining) /
            (Fintype.card Output : ℝ) ^ (remaining + 1) := by
          exact div_le_div_of_nonneg_right cardBoundReal (by positivity)
        _ = (remaining + 1 : ℝ) / Fintype.card Output := by
          field_simp
          ring

/-- Squared Euclidean norm of a finite complex vector. -/
def vectorNormSquared
    (vector : Context → ℂ) : ℝ :=
  ∑ context : Context, Complex.normSq (vector context)

/-- A finite vector represented in Mathlib's Euclidean-space type. -/
def euclideanVector
    (vector : Context → ℂ) :
    EuclideanSpace ℂ Context :=
  WithLp.toLp 2 vector

@[simp]
theorem euclidean_vector_apply
    (vector : Context → ℂ)
    (context : Context) :
    euclideanVector vector context = vector context := by
  rfl

/-- The explicit finite squared norm agrees with the Hilbert-space norm. -/
theorem euclidean_vector_norm_sq
    (vector : Context → ℂ) :
    ‖euclideanVector vector‖ ^ 2 = vectorNormSquared vector := by
  unfold vectorNormSquared
  rw [EuclideanSpace.norm_sq_eq]
  apply Finset.sum_congr rfl
  intro context _
  exact Complex.sq_norm (vector context)

/-- The square root of the explicit squared norm is the Euclidean norm. -/
theorem sqrt_vector_norm_squared
    (vector : Context → ℂ) :
    Real.sqrt (vectorNormSquared vector) = ‖euclideanVector vector‖ := by
  rw [← euclidean_vector_norm_sq]
  exact Real.sqrt_sq (norm_nonneg _)

/-- Triangle inequality stated directly in the probability-amplitude form used by Lemma 5. -/
theorem sqrt_vector_norm_triangle
    (left right : Context → ℂ) :
    Real.sqrt (vectorNormSquared (left + right)) ≤
      Real.sqrt (vectorNormSquared left) +
        Real.sqrt (vectorNormSquared right) := by
  simp_rw [sqrt_vector_norm_squared]
  exact norm_add_le (euclideanVector left) (euclideanVector right)

/-- Normalized Fourier sum over every index. -/
def allFourierAmplitude
    (remaining : Nat)
    (normalization : ℂ)
    (coefficient : Context → (Fin (remaining + 1) → Output) → ℂ) :
    Context → ℂ :=
  fun context =>
    normalization *
      ∑ index : Fin (remaining + 1) → Output,
        coefficient context index

/-- Normalized Fourier sum over indices with no zero coordinate. -/
def recordedFourierAmplitude
    (remaining : Nat)
    (zero : Output)
    (normalization : ℂ)
    (coefficient : Context → (Fin (remaining + 1) → Output) → ℂ) :
    Context → ℂ :=
  fun context =>
    normalization *
      ∑ index ∈
          (Finset.univ.filter fun index : Fin (remaining + 1) → Output =>
            ¬∃ coordinate, index coordinate = zero),
        coefficient context index

/-- Normalized Fourier sum over indices with at least one zero coordinate. -/
def omittedFourierAmplitude
    (remaining : Nat)
    (zero : Output)
    (normalization : ℂ)
    (coefficient : Context → (Fin (remaining + 1) → Output) → ℂ) :
    Context → ℂ :=
  fun context =>
    normalization *
      ∑ index ∈ zeroCoordinateIndices (remaining + 1) zero,
        coefficient context index

set_option maxHeartbeats 800000 in
/-- The complete Fourier amplitude splits exactly into recorded and omitted indices. -/
theorem all_fourier_amplitude_eq_recorded_add_omitted
    (remaining : Nat)
    (zero : Output)
    (normalization : ℂ)
    (coefficient : Context → (Fin (remaining + 1) → Output) → ℂ) :
    allFourierAmplitude remaining normalization coefficient =
      recordedFourierAmplitude remaining zero normalization coefficient +
        omittedFourierAmplitude remaining zero normalization coefficient := by
  funext context
  unfold allFourierAmplitude recordedFourierAmplitude omittedFourierAmplitude
    zeroCoordinateIndices
  rw [Pi.add_apply]
  have partition :=
    Finset.sum_filter_add_sum_filter_not
      (Finset.univ : Finset (Fin (remaining + 1) → Output))
      (fun index => ∃ coordinate, index coordinate = zero)
      (fun index => coefficient context index)
  calc
    normalization * ∑ index, coefficient context index =
        normalization *
          ((∑ index with ∃ coordinate, index coordinate = zero,
              coefficient context index) +
            ∑ index with ¬∃ coordinate, index coordinate = zero,
              coefficient context index) :=
      congrArg (fun value => normalization * value) partition.symm
    _ =
        normalization *
            (∑ index with ¬∃ coordinate, index coordinate = zero,
              coefficient context index) +
          normalization *
            ∑ index with ∃ coordinate, index coordinate = zero,
              coefficient context index := by
      rw [mul_add, add_comm]

/--
Published oracle-to-database amplitude inequality in its exact finite coefficient form.

The left side is the random-oracle success amplitude, the first right-hand term is the
measured compressed-database success amplitude, and the final term is the exact
`sqrt(k / |Y|)` bridge loss.
-/
theorem oracle_to_database_amplitude_bridge
    (remaining : Nat)
    (zero : Output)
    (normalization : ℂ)
    (normalizationNorm :
      Complex.normSq normalization =
        1 / (Fintype.card Output : ℝ) ^ (remaining + 1))
    (coefficient : Context → (Fin (remaining + 1) → Output) → ℂ)
    (subnormalized :
      (∑ context : Context,
        ∑ index : Fin (remaining + 1) → Output,
          Complex.normSq (coefficient context index)) ≤ 1) :
    Real.sqrt
        (vectorNormSquared
          (allFourierAmplitude remaining normalization coefficient)) ≤
      Real.sqrt
          (vectorNormSquared
            (recordedFourierAmplitude remaining zero normalization coefficient)) +
        Real.sqrt ((remaining + 1 : ℝ) / Fintype.card Output) := by
  let omitted :=
    omittedFourierAmplitude remaining zero normalization coefficient
  have omittedBound :
      vectorNormSquared omitted ≤
        (remaining + 1 : ℝ) / Fintype.card Output := by
    simpa [vectorNormSquared, omitted, omittedFourierAmplitude] using
      zero_coordinate_fourier_mass_le
        (Context := Context) remaining zero normalization normalizationNorm
          coefficient subnormalized
  have triangle :=
    sqrt_vector_norm_triangle
      (recordedFourierAmplitude remaining zero normalization coefficient)
      omitted
  rw [← all_fourier_amplitude_eq_recorded_add_omitted
    remaining zero normalization coefficient] at triangle
  exact triangle.trans
    (add_le_add_right (Real.sqrt_le_sqrt omittedBound) _)

section ConcreteDecompression

variable [AddCommGroup Output]

section SelectedCoordinates

variable {Input : Type*}
variable [Fintype Input] [DecidableEq Input]

/--
The oracle inputs outside one injectively enumerated tuple of claims.

Keeping this as an actual finite subtype, rather than an informal "rest of the
database", lets later probability sums be reindexed without dropping or
duplicating any database basis state.
-/
def OutsideInput
    {arity : Nat}
    (selected : Fin arity → Input) :=
  { input : Input // ∀ coordinate, selected coordinate ≠ input }

/--
An injective tuple of selected inputs and its complement partition the complete
finite oracle domain.
-/
def splitInputEquiv
    {arity : Nat}
    (selected : Fin arity → Input)
    (injective : Function.Injective selected) :
    (Fin arity ⊕ OutsideInput selected) ≃ Input :=
  Equiv.ofBijective
    (fun location =>
      match location with
      | Sum.inl coordinate => selected coordinate
      | Sum.inr outside => outside.1)
    (by
      constructor
      · intro left right same
        cases left with
        | inl leftCoordinate =>
            cases right with
            | inl rightCoordinate =>
                exact congrArg Sum.inl (injective same)
            | inr rightOutside =>
                exact
                  (rightOutside.2 leftCoordinate same).elim
        | inr leftOutside =>
            cases right with
            | inl rightCoordinate =>
                exact
                  (leftOutside.2 rightCoordinate same.symm).elim
            | inr rightOutside =>
                have outsideEqual : leftOutside = rightOutside :=
                  Subtype.ext same
                cases outsideEqual
                rfl
      · intro input
        by_cases selectedInput : ∃ coordinate, selected coordinate = input
        · obtain ⟨coordinate, coordinateInput⟩ := selectedInput
          exact ⟨Sum.inl coordinate, coordinateInput⟩
        · let outside : OutsideInput selected :=
            ⟨input, fun coordinate same =>
              selectedInput ⟨coordinate, same⟩⟩
          exact ⟨Sum.inr outside, rfl⟩)

/--
Canonical database reindexing into all selected coordinates and all remaining
coordinates.  This is an equivalence of the complete function spaces, not a
support restriction.
-/
def databaseSplitEquiv
    {arity : Nat}
    (selected : Fin arity → Input)
    (injective : Function.Injective selected) :
    HegemonCrypto.FiniteOracleDatabase.Database Input Output ≃
      ((Fin arity → Option Output) ×
        (OutsideInput selected → Option Output)) :=
  (Equiv.arrowCongr
      (splitInputEquiv selected injective).symm
      (Equiv.refl (Option Output))).trans
    (Equiv.sumArrowEquivProdArrow
      (Fin arity) (OutsideInput selected) (Option Output))

@[simp]
theorem database_split_equiv_selected
    {arity : Nat}
    (selected : Fin arity → Input)
    (injective : Function.Injective selected)
    (database :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output)
    (coordinate : Fin arity) :
    (databaseSplitEquiv selected injective database).1 coordinate =
      database (selected coordinate) := by
  rfl

@[simp]
theorem database_split_equiv_outside
    {arity : Nat}
    (selected : Fin arity → Input)
    (injective : Function.Injective selected)
    (database :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output)
    (outside : OutsideInput selected) :
    (databaseSplitEquiv selected injective database).2 outside =
      database outside.1 := by
  simp [databaseSplitEquiv, splitInputEquiv]

end SelectedCoordinates

/--
On a total-oracle fiber, one selected compressed-database coordinate differs from the
corresponding real-oracle coordinate by exactly the normalized sum of the fiber.
-/
theorem total_fiber_coordinate_difference
    (state : FiberState Output)
    (output : Output)
    (totalSupport : state none = 0) :
    state (some output) - decompressFiber state (some output) =
      inverseOutputCard (Output := Output) *
        ∑ recorded : Output, state (some recorded) := by
  rw [decompress_fiber_apply_some, totalSupport]
  ring

/--
Concrete one-claim bridge bound for the implemented CMS decompression reflection.
This is the `k = 1` state-level base case of Zhandry Lemma 5.
-/
theorem total_fiber_coordinate_difference_normSq_le
    (state : FiberState Output)
    (output : Output)
    (totalSupport : state none = 0) :
    Complex.normSq
        (state (some output) - decompressFiber state (some output)) ≤
      (1 / (Fintype.card Output : ℝ)) * ‖state‖ ^ 2 := by
  rw [total_fiber_coordinate_difference state output totalSupport]
  rw [Complex.normSq_mul, normSq_inverseOutputCard]
  have cauchy :=
    normSq_sum_le_card_mul_sum_normSq
      (Finset.univ : Finset Output)
      (fun recorded => state (some recorded))
  have cardPositive : (0 : ℝ) < Fintype.card Output :=
    output_card_real_positive (Output := Output)
  calc
    (1 / (Fintype.card Output : ℝ) ^ 2) *
        Complex.normSq (∑ recorded : Output, state (some recorded)) ≤
      (1 / (Fintype.card Output : ℝ) ^ 2) *
        ((Fintype.card Output : ℝ) *
          ∑ recorded : Output,
            Complex.normSq (state (some recorded))) := by
      exact mul_le_mul_of_nonneg_left cauchy (by positivity)
    _ =
      (1 / (Fintype.card Output : ℝ)) *
        ∑ recorded : Output,
          Complex.normSq (state (some recorded)) := by
      field_simp
    _ ≤
      (1 / (Fintype.card Output : ℝ)) *
        ‖state‖ ^ 2 := by
      apply mul_le_mul_of_nonneg_left
      · rw [EuclideanSpace.norm_sq_eq, Fintype.sum_option]
        simp_rw [Complex.sq_norm]
        simp [totalSupport]
      · positivity

section StateLevelBridge

variable {Input Phase Workspace : Type*}
variable [Fintype Input] [DecidableEq Input]
variable [Fintype Phase] [DecidableEq Phase]
variable [Fintype Workspace] [DecidableEq Workspace]

/-- Keep only basis states whose database records one named oracle answer. -/
def coordinateEventProjection
    (selectedInput : Input)
    (selectedOutput : Output)
    (state : State Input Output Phase Workspace) :
    State Input Output Phase Workspace :=
  fun basis =>
    if basis.database selectedInput = some selectedOutput then
      state basis
    else
      0

/-- A state is total at one oracle input when no absent-coordinate branch has amplitude. -/
def TotalAt
    (selectedInput : Input)
    (state : State Input Output Phase Workspace) : Prop :=
  ∀ basis,
    basis.database selectedInput = none →
      state basis = 0

/--
The coordinate-event probability is exactly the sum of the selected fiber
coordinate over all adversary registers and all databases outside that input.
-/
theorem norm_squared_coordinate_event_projection
    (selectedInput : Input)
    (selectedOutput : Output)
    (state : State Input Output Phase Workspace) :
    normSquared
        (coordinateEventProjection selectedInput selectedOutput state) =
      ∑ registerInput : Input,
        ∑ phaseValue : Phase,
          ∑ workspace : Workspace,
            ∑ base :
                HegemonCrypto.DatabaseFiber.AbsentDatabase
                  (Output := Output) selectedInput,
              Complex.normSq
                (databaseFiberState state registerInput phaseValue workspace
                  selectedInput base (some selectedOutput)) := by
  unfold normSquared
  rw [← (basisEquiv (Input := Input) (Output := Output) (Phase := Phase)
    (Workspace := Workspace)).sum_comp
      (fun basis =>
        Complex.normSq
          (coordinateEventProjection selectedInput selectedOutput state basis))]
  rw [Fintype.sum_prod_type]
  apply Finset.sum_congr rfl
  intro registerInput _
  rw [Fintype.sum_prod_type]
  apply Finset.sum_congr rfl
  intro phaseValue _
  rw [Fintype.sum_prod_type]
  apply Finset.sum_congr rfl
  intro workspace _
  rw [HegemonCrypto.DatabaseFiber.sum_database_eq_sum_fibers]
  apply Finset.sum_congr rfl
  intro base _
  have absentProjection :
      coordinateEventProjection selectedInput selectedOutput state
          (basisEquiv (registerInput, phaseValue, workspace, base.1)) = 0 := by
    unfold coordinateEventProjection basisEquiv
    simp [base.2]
  rw [absentProjection, map_zero, zero_add]
  rw [Finset.sum_eq_single selectedOutput]
  · simp [coordinateEventProjection, basisEquiv,
      database_fiber_state_apply,
      HegemonCrypto.DatabaseFiber.databaseEquiv_symm_some]
  · intro candidate _ different
    simp [coordinateEventProjection, basisEquiv, different]
  · simp

/--
One selected coordinate of the concrete decompression reflection changes the
corresponding event vector by squared norm at most `1 / |Y|` of the complete
state norm.
-/
theorem coordinate_event_decompression_difference_norm_squared_le
    (selectedInput : Input)
    (selectedOutput : Output)
    (state : State Input Output Phase Workspace)
    (total : TotalAt selectedInput state) :
    normSquared
        (fun basis =>
          coordinateEventProjection selectedInput selectedOutput state basis -
            coordinateEventProjection selectedInput selectedOutput
              (decompressAt selectedInput state) basis) ≤
      (1 / (Fintype.card Output : ℝ)) * normSquared state := by
  let differenceState : State Input Output Phase Workspace :=
    fun basis =>
      state basis - decompressAt selectedInput state basis
  have projectionDifference :
      (fun basis =>
        coordinateEventProjection selectedInput selectedOutput state basis -
          coordinateEventProjection selectedInput selectedOutput
            (decompressAt selectedInput state) basis) =
        coordinateEventProjection selectedInput selectedOutput differenceState := by
    funext basis
    unfold coordinateEventProjection differenceState
    by_cases recorded :
        basis.database selectedInput = some selectedOutput <;>
      simp [recorded]
  rw [projectionDifference,
    norm_squared_coordinate_event_projection
      selectedInput selectedOutput differenceState,
    norm_squared_eq_sum_database_fiber_norm selectedInput state,
    Finset.mul_sum]
  apply Finset.sum_le_sum
  intro registerInput _
  rw [Finset.mul_sum]
  apply Finset.sum_le_sum
  intro phaseValue _
  rw [Finset.mul_sum]
  apply Finset.sum_le_sum
  intro workspace _
  rw [Finset.mul_sum]
  apply Finset.sum_le_sum
  intro base _
  have totalSupport :
      databaseFiberState state registerInput phaseValue workspace
          selectedInput base none = 0 := by
    apply total
    exact base.2
  have fiberBound :=
    total_fiber_coordinate_difference_normSq_le
      (databaseFiberState state registerInput phaseValue workspace
        selectedInput base)
      selectedOutput totalSupport
  change
    Complex.normSq
        (databaseFiberState state registerInput phaseValue workspace
            selectedInput base (some selectedOutput) -
          databaseFiberState (decompressAt selectedInput state)
            registerInput phaseValue workspace selectedInput base
              (some selectedOutput)) ≤
      1 / ↑(Fintype.card Output) *
        ‖databaseFiberState state registerInput phaseValue workspace
          selectedInput base‖ ^ 2
  rw [database_fiber_state_decompress_at]
  exact fiberBound

/-- Keep exactly the database branches satisfying an arbitrary finite event. -/
def databaseEventProjection
    (event :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output → Prop)
    (state : State Input Output Phase Workspace) :
    State Input Output Phase Workspace :=
  fun basis =>
    @ite ℂ (event basis.database) (Classical.propDecidable _)
      (state basis) 0

/-- A computational-basis event projection cannot increase squared norm. -/
theorem database_event_projection_norm_squared_le
    (event :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output → Prop)
    (state : State Input Output Phase Workspace) :
    normSquared (databaseEventProjection event state) ≤ normSquared state := by
  unfold normSquared
  apply Finset.sum_le_sum
  intro basis _
  by_cases accepted : event basis.database
  · simp [databaseEventProjection, accepted]
  · simp [databaseEventProjection, accepted, Complex.normSq_nonneg]

/--
Projecting onto a narrower database event cannot enlarge the one-coordinate
decompression difference.
-/
theorem database_event_decompression_difference_norm_squared_le
    (event :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output → Prop)
    (selectedInput : Input)
    (selectedOutput : Output)
    (eventRecords :
      ∀ database, event database →
        database selectedInput = some selectedOutput)
    (state : State Input Output Phase Workspace)
    (total : TotalAt selectedInput state) :
    normSquared
        (fun basis =>
          databaseEventProjection event state basis -
            databaseEventProjection event
              (decompressAt selectedInput state) basis) ≤
      (1 / (Fintype.card Output : ℝ)) * normSquared state := by
  let coordinateDifference : State Input Output Phase Workspace :=
    fun basis =>
      coordinateEventProjection selectedInput selectedOutput state basis -
        coordinateEventProjection selectedInput selectedOutput
          (decompressAt selectedInput state) basis
  have eventDifference :
      (fun basis =>
        databaseEventProjection event state basis -
          databaseEventProjection event
            (decompressAt selectedInput state) basis) =
        databaseEventProjection event coordinateDifference := by
    funext basis
    by_cases accepted : event basis.database
    · have recorded := eventRecords basis.database accepted
      simp [databaseEventProjection, coordinateDifference,
        coordinateEventProjection, accepted, recorded]
    · simp [databaseEventProjection, accepted]
  rw [eventDifference]
  exact
    (database_event_projection_norm_squared_le event coordinateDifference).trans
      (coordinate_event_decompression_difference_norm_squared_le
        selectedInput selectedOutput state total)

/-- Decompression at another coordinate preserves total support at this one. -/
theorem total_at_decompress_at_of_ne
    (changedInput preservedInput : Input)
    (state : State Input Output Phase Workspace)
    (different : changedInput ≠ preservedInput)
    (total : TotalAt preservedInput state) :
    TotalAt preservedInput (decompressAt changedInput state) := by
  intro target preservedAbsent
  rw [decompress_at_eq_sum_kernel]
  apply Finset.sum_eq_zero
  intro source _
  have sourceAbsent :
      (setDatabaseCoordinate target.database changedInput source)
          preservedInput = none := by
    rw [set_database_coordinate_other target.database
      (Ne.symm different) source]
    exact preservedAbsent
  rw [total
    { input := target.input
      phase := target.phase
      workspace := target.workspace
      database :=
        setDatabaseCoordinate target.database changedInput source }
    sourceAbsent]
  simp

/-- Decompressions away from one coordinate preserve total support there. -/
theorem total_at_decompress_list_of_not_mem
    (preservedInput : Input)
    (inputs : List Input)
    (state : State Input Output Phase Workspace)
    (omitted : preservedInput ∉ inputs)
    (total : TotalAt preservedInput state) :
    TotalAt preservedInput (decompressList inputs state) := by
  induction inputs with
  | nil =>
      exact total
  | cons changedInput remaining inductionHypothesis =>
      have changedDifferent : changedInput ≠ preservedInput := by
        intro same
        apply omitted
        simp [same]
      have remainingOmitted : preservedInput ∉ remaining := by
        intro member
        apply omitted
        simp [member]
      rw [decompress_list_cons]
      exact total_at_decompress_at_of_ne
        changedInput preservedInput
        (decompressList remaining state)
        changedDifferent
        (inductionHypothesis remainingOmitted)

/-- Every finite product of concrete decompressions preserves squared norm. -/
theorem decompress_list_preserves_norm_squared
    (inputs : List Input)
    (state : State Input Output Phase Workspace) :
    normSquared (decompressList inputs state) = normSquared state := by
  induction inputs with
  | nil =>
      rfl
  | cons input remaining inductionHypothesis =>
      rw [decompress_list_cons,
        decompress_at_preserves_norm_squared,
        inductionHypothesis]

/-- Triangle inequality for finite compressed-oracle states in amplitude form. -/
theorem sqrt_norm_squared_state_triangle
    (left right : State Input Output Phase Workspace) :
    Real.sqrt (normSquared (fun basis => left basis + right basis)) ≤
      Real.sqrt (normSquared left) + Real.sqrt (normSquared right) := by
  simpa [normSquared, vectorNormSquared] using
    sqrt_vector_norm_triangle
      (Context := Basis Input Output Phase Workspace) left right

/-- Distance between one database event before and after a decompression list. -/
def eventDecompressionDistanceSquared
    (event :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output → Prop)
    (inputs : List Input)
    (state : State Input Output Phase Workspace) : ℝ :=
  normSquared
    (fun basis =>
      databaseEventProjection event state basis -
        databaseEventProjection event
          (decompressList inputs state) basis)

/--
Conservative fully state-level oracle-to-database bridge.

For a duplicate-free list of claimed inputs, each event claim records its named
output and the initial state is total at every claimed input.  The event-vector
distance after concrete decompression is at most

`inputs.length * sqrt(normSquared state / |Y|)`.

This is weaker than the tight published `sqrt(k / |Y|)` term by a factor
`sqrt(k)`, but it follows directly from the implemented Householder reflection
and is already negligible for the active 512-bit oracle.
-/
theorem event_decompression_distance_amplitude_le
    (event :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output → Prop)
    (claims : List (Input × Output))
    (state : State Input Output Phase Workspace)
    (distinctInputs : (claims.map Prod.fst).Nodup)
    (eventRecords :
      ∀ claim ∈ claims,
        ∀ database, event database →
          database claim.1 = some claim.2)
    (total :
      ∀ claim ∈ claims, TotalAt claim.1 state) :
    Real.sqrt
        (eventDecompressionDistanceSquared event
          (claims.map Prod.fst) state) ≤
      claims.length *
        Real.sqrt
          ((1 / (Fintype.card Output : ℝ)) * normSquared state) := by
  induction claims with
  | nil =>
      simp [eventDecompressionDistanceSquared, normSquared]
  | cons claim remaining inductionHypothesis =>
      have distinctParts :
          claim.1 ∉ remaining.map Prod.fst ∧
            (remaining.map Prod.fst).Nodup := by
        simpa using distinctInputs
      have claimNotRemaining :
          claim.1 ∉ remaining.map Prod.fst := by
        exact distinctParts.1
      have remainingDistinct :
          (remaining.map Prod.fst).Nodup := by
        exact distinctParts.2
      have remainingEventRecords :
          ∀ selected ∈ remaining,
            ∀ database, event database →
              database selected.1 = some selected.2 := by
        intro selected selectedMember
        exact eventRecords selected (by simp [selectedMember])
      have remainingTotal :
          ∀ selected ∈ remaining, TotalAt selected.1 state := by
        intro selected selectedMember
        exact total selected (by simp [selectedMember])
      have tailBound :=
        inductionHypothesis remainingDistinct
          remainingEventRecords remainingTotal
      let tailState :=
        decompressList (remaining.map Prod.fst) state
      have headTotal : TotalAt claim.1 tailState := by
        exact total_at_decompress_list_of_not_mem
          claim.1 (remaining.map Prod.fst) state claimNotRemaining
          (total claim (by simp))
      have headRecords :
          ∀ database, event database →
            database claim.1 = some claim.2 :=
        eventRecords claim (by simp)
      have headDifference :=
        database_event_decompression_difference_norm_squared_le
          event claim.1 claim.2 headRecords tailState headTotal
      have tailNorm :
          normSquared tailState = normSquared state :=
        decompress_list_preserves_norm_squared
          (remaining.map Prod.fst) state
      have decomposition :
          (fun basis =>
            databaseEventProjection event state basis -
              databaseEventProjection event
                (decompressList
                  ((claim :: remaining).map Prod.fst) state) basis) =
            fun basis =>
              (databaseEventProjection event state basis -
                databaseEventProjection event tailState basis) +
              (databaseEventProjection event tailState basis -
                databaseEventProjection event
                  (decompressAt claim.1 tailState) basis) := by
        funext basis
        simp only [List.map_cons, decompress_list_cons, tailState]
        ring
      unfold eventDecompressionDistanceSquared
      rw [decomposition]
      calc
        Real.sqrt
            (normSquared fun basis =>
              (databaseEventProjection event state basis -
                  databaseEventProjection event tailState basis) +
                (databaseEventProjection event tailState basis -
                  databaseEventProjection event
                    (decompressAt claim.1 tailState) basis)) ≤
            Real.sqrt
                (normSquared fun basis =>
                  databaseEventProjection event state basis -
                    databaseEventProjection event tailState basis) +
              Real.sqrt
                (normSquared fun basis =>
                  databaseEventProjection event tailState basis -
                    databaseEventProjection event
                      (decompressAt claim.1 tailState) basis) :=
          sqrt_norm_squared_state_triangle _ _
        _ ≤
            remaining.length *
                Real.sqrt
                  (1 / ↑(Fintype.card Output) * normSquared state) +
              Real.sqrt
                (1 / ↑(Fintype.card Output) * normSquared tailState) := by
          apply add_le_add tailBound
          exact Real.sqrt_le_sqrt headDifference
        _ =
            (claim :: remaining).length *
              Real.sqrt
                (1 / ↑(Fintype.card Output) * normSquared state) := by
          rw [tailNorm]
          simp only [List.length_cons, Nat.cast_add, Nat.cast_one]
          ring

/--
Probability-amplitude form of the conservative state-level bridge.
-/
theorem event_probability_decompression_amplitude_le
    (event :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output → Prop)
    (claims : List (Input × Output))
    (state : State Input Output Phase Workspace)
    (distinctInputs : (claims.map Prod.fst).Nodup)
    (eventRecords :
      ∀ claim ∈ claims,
        ∀ database, event database →
          database claim.1 = some claim.2)
    (total :
      ∀ claim ∈ claims, TotalAt claim.1 state) :
    Real.sqrt
        (normSquared (databaseEventProjection event state)) ≤
      Real.sqrt
          (normSquared
            (databaseEventProjection event
              (decompressList (claims.map Prod.fst) state))) +
        claims.length *
          Real.sqrt
            ((1 / (Fintype.card Output : ℝ)) * normSquared state) := by
  let finalState :=
    decompressList (claims.map Prod.fst) state
  let differenceState : State Input Output Phase Workspace :=
    fun basis =>
      databaseEventProjection event state basis -
        databaseEventProjection event finalState basis
  have decomposition :
      databaseEventProjection event state =
        fun basis =>
          databaseEventProjection event finalState basis +
            differenceState basis := by
    funext basis
    unfold differenceState
    ring
  rw [decomposition]
  calc
    Real.sqrt
        (normSquared fun basis =>
          databaseEventProjection event finalState basis +
            differenceState basis) ≤
      Real.sqrt
          (normSquared (databaseEventProjection event finalState)) +
        Real.sqrt (normSquared differenceState) :=
      sqrt_norm_squared_state_triangle _ _
    _ ≤
      Real.sqrt
          (normSquared
            (databaseEventProjection event
              (decompressList (claims.map Prod.fst) state))) +
        claims.length *
          Real.sqrt
            ((1 / (Fintype.card Output : ℝ)) * normSquared state) := by
      apply add_le_add
      · rfl
      · simpa [differenceState, finalState,
          eventDecompressionDistanceSquared] using
          event_decompression_distance_amplitude_le
            event claims state distinctInputs eventRecords total

/--
Normalized-state specialization.  The only bridge loss is the explicit finite
output-space term `k / sqrt(|Y|)`.
-/
theorem normalized_event_probability_decompression_amplitude_le
    (event :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output → Prop)
    (claims : List (Input × Output))
    (state : State Input Output Phase Workspace)
    (distinctInputs : (claims.map Prod.fst).Nodup)
    (eventRecords :
      ∀ claim ∈ claims,
        ∀ database, event database →
          database claim.1 = some claim.2)
    (total :
      ∀ claim ∈ claims, TotalAt claim.1 state)
    (normalized : normSquared state ≤ 1) :
    Real.sqrt
        (normSquared (databaseEventProjection event state)) ≤
      Real.sqrt
          (normSquared
            (databaseEventProjection event
              (decompressList (claims.map Prod.fst) state))) +
        claims.length *
          Real.sqrt (1 / (Fintype.card Output : ℝ)) := by
  have bridge :=
    event_probability_decompression_amplitude_le
      event claims state distinctInputs eventRecords total
  apply bridge.trans
  apply add_le_add
  · rfl
  · apply mul_le_mul_of_nonneg_left _ (by positivity)
    apply Real.sqrt_le_sqrt
    exact mul_le_of_le_one_right (by positivity) normalized

/-- A purified total-oracle family has no absent branch at any oracle input. -/
theorem total_oracle_family_state_total_at
    (family : OracleRegisterFamily
      (Input := Input) (Output := Output) (Phase := Phase)
      (Workspace := Workspace))
    (selectedInput : Input) :
    TotalAt selectedInput (totalOracleFamilyState family) := by
  intro basis absent
  apply total_oracle_family_state_eq_zero_of_no_match
  intro matched
  obtain ⟨oracle, databaseEqual⟩ := matched
  have atInput := congrArg (fun database => database selectedInput) databaseEqual
  simp [totalDatabase, absent] at atInput

/-- Exact database event that all named oracle claims are recorded. -/
def ClaimsDatabaseEvent
    (claims : List (Input × Output))
    (database :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output) : Prop :=
  ∀ claim ∈ claims, database claim.1 = some claim.2

/-- Replacing an unclaimed database coordinate preserves the complete claim event. -/
theorem claims_database_event_set_coordinate_iff_of_not_mem
    (claims : List (Input × Output))
    (database :
      HegemonCrypto.FiniteOracleDatabase.Database Input Output)
    (changedInput : Input)
    (coordinate : Option Output)
    (unclaimed : changedInput ∉ claims.map Prod.fst) :
    ClaimsDatabaseEvent claims
        (setDatabaseCoordinate database changedInput coordinate) ↔
      ClaimsDatabaseEvent claims database := by
  constructor
  · intro records claim member
    have claimDifferent : claim.1 ≠ changedInput := by
      intro same
      apply unclaimed
      exact List.mem_map.mpr ⟨claim, member, same⟩
    simpa [ClaimsDatabaseEvent,
      set_database_coordinate_other database claimDifferent coordinate] using
      records claim member
  · intro records claim member
    have claimDifferent : claim.1 ≠ changedInput := by
      intro same
      apply unclaimed
      exact List.mem_map.mpr ⟨claim, member, same⟩
    simpa [ClaimsDatabaseEvent,
      set_database_coordinate_other database claimDifferent coordinate] using
      records claim member

/--
The claims projector commutes exactly with decompression at an unclaimed oracle
input.
-/
theorem claims_event_projection_decompress_at_of_not_mem
    (claims : List (Input × Output))
    (changedInput : Input)
    (state : State Input Output Phase Workspace)
    (unclaimed : changedInput ∉ claims.map Prod.fst) :
    databaseEventProjection (ClaimsDatabaseEvent claims)
        (decompressAt changedInput state) =
      decompressAt changedInput
        (databaseEventProjection (ClaimsDatabaseEvent claims) state) := by
  funext target
  rw [decompress_at_eq_sum_kernel]
  unfold databaseEventProjection
  by_cases targetRecords : ClaimsDatabaseEvent claims target.database
  · rw [if_pos targetRecords, decompress_at_eq_sum_kernel]
    apply Finset.sum_congr rfl
    intro source _
    have sourceRecords :
        ClaimsDatabaseEvent claims
          (setDatabaseCoordinate target.database changedInput source) :=
      (claims_database_event_set_coordinate_iff_of_not_mem
        claims target.database changedInput source unclaimed).mpr targetRecords
    rw [if_pos sourceRecords]
  · rw [if_neg targetRecords]
    symm
    apply Finset.sum_eq_zero
    intro source _
    have sourceDoesNotRecord :
        ¬ClaimsDatabaseEvent claims
          (setDatabaseCoordinate target.database changedInput source) := by
      intro sourceRecords
      exact targetRecords
        ((claims_database_event_set_coordinate_iff_of_not_mem
          claims target.database changedInput source unclaimed).mp sourceRecords)
    rw [if_neg sourceDoesNotRecord]
    simp

/-- Unclaimed decompression preserves the exact claims-event probability. -/
theorem claims_event_projection_norm_decompress_at_of_not_mem
    (claims : List (Input × Output))
    (changedInput : Input)
    (state : State Input Output Phase Workspace)
    (unclaimed : changedInput ∉ claims.map Prod.fst) :
    normSquared
        (databaseEventProjection (ClaimsDatabaseEvent claims)
          (decompressAt changedInput state)) =
      normSquared
        (databaseEventProjection (ClaimsDatabaseEvent claims) state) := by
  rw [claims_event_projection_decompress_at_of_not_mem
    claims changedInput state unclaimed]
  exact decompress_at_preserves_norm_squared changedInput _

/-- A list of unclaimed decompressions preserves the claims-event probability. -/
theorem claims_event_projection_norm_decompress_list_of_outside
    (claims : List (Input × Output))
    (inputs : List Input)
    (state : State Input Output Phase Workspace)
    (outside :
      ∀ input ∈ inputs, input ∉ claims.map Prod.fst) :
    normSquared
        (databaseEventProjection (ClaimsDatabaseEvent claims)
          (decompressList inputs state)) =
      normSquared
        (databaseEventProjection (ClaimsDatabaseEvent claims) state) := by
  induction inputs with
  | nil =>
      rfl
  | cons input remaining inductionHypothesis =>
      have inputOutside : input ∉ claims.map Prod.fst :=
        outside input (by simp)
      have remainingOutside :
          ∀ selected ∈ remaining, selected ∉ claims.map Prod.fst := by
        intro selected member
        exact outside selected (by simp [member])
      rw [decompress_list_cons,
        claims_event_projection_norm_decompress_at_of_not_mem
          claims input (decompressList remaining state) inputOutside,
        inductionHypothesis remainingOutside]

/-- Decompression over concatenated input lists composes in fold-right order. -/
theorem decompress_list_append
    (left right : List Input)
    (state : State Input Output Phase Workspace) :
    decompressList (left ++ right) state =
      decompressList left (decompressList right state) := by
  induction left with
  | nil =>
      rfl
  | cons input remaining inductionHypothesis =>
      simp only [List.cons_append, decompress_list_cons]
      rw [inductionHypothesis]

/-- Inputs outside the finite claim set. -/
def outsideClaimInputs
    (claims : List (Input × Output)) : List Input :=
  ((Finset.univ : Finset Input) \ (claims.map Prod.fst).toFinset).toList

theorem outside_claim_inputs_are_unclaimed
    (claims : List (Input × Output))
    (input : Input)
    (member : input ∈ outsideClaimInputs claims) :
    input ∉ claims.map Prod.fst := by
  simpa [outsideClaimInputs] using member

/--
For duplicate-free claims, the unclaimed inputs followed by the claimed inputs
are a permutation of the complete finite oracle domain.
-/
theorem outside_append_claim_inputs_perm_univ
    (claims : List (Input × Output))
    (distinctInputs : (claims.map Prod.fst).Nodup) :
    (outsideClaimInputs claims ++ claims.map Prod.fst).Perm
      (Finset.univ : Finset Input).toList := by
  apply List.perm_of_nodup_nodup_toFinset_eq
  · apply List.nodup_append.mpr
    refine ⟨((
      (Finset.univ : Finset Input) \
        (claims.map Prod.fst).toFinset).nodup_toList),
      distinctInputs, ?_⟩
    intro outsideInput outsideMember claimedInput claimMember equalInputs
    subst claimedInput
    exact
      (outside_claim_inputs_are_unclaimed claims outsideInput outsideMember)
        claimMember
  · exact (Finset.univ : Finset Input).nodup_toList
  · ext input
    simp [outsideClaimInputs]

/--
The full decompression has exactly the same claims-event probability as
decompressing only the claimed coordinates.  Every omitted coordinate acts
unitarily inside each claim-event subspace.
-/
theorem claims_event_projection_norm_global_decompress_eq_selected
    (claims : List (Input × Output))
    (state : State Input Output Phase Workspace)
    (distinctInputs : (claims.map Prod.fst).Nodup) :
    normSquared
        (databaseEventProjection (ClaimsDatabaseEvent claims)
          (globalDecompress state)) =
      normSquared
        (databaseEventProjection (ClaimsDatabaseEvent claims)
          (decompressList (claims.map Prod.fst) state)) := by
  have permutation :=
    outside_append_claim_inputs_perm_univ claims distinctInputs
  have reordered :
      globalDecompress state =
        decompressList
          (outsideClaimInputs claims ++ claims.map Prod.fst) state := by
    unfold globalDecompress
    exact (decompress_list_perm permutation state).symm
  rw [reordered, decompress_list_append]
  exact
    claims_event_projection_norm_decompress_list_of_outside
      claims (outsideClaimInputs claims)
      (decompressList (claims.map Prod.fst) state)
      (fun input member =>
        outside_claim_inputs_are_unclaimed claims input member)

/-- A finite product of commuting decompression involutions is itself involutive. -/
theorem decompress_list_involutive
    (inputs : List Input)
    (state : State Input Output Phase Workspace) :
    decompressList inputs (decompressList inputs state) = state := by
  induction inputs with
  | nil =>
      rfl
  | cons input remaining inductionHypothesis =>
      simp only [decompress_list_cons]
      rw [← decompress_at_decompress_list_commutes
        input remaining (decompressList remaining state)]
      rw [decompress_at_involutive]
      exact inductionHypothesis

/-- Full finite-domain decompression is an exact involution. -/
theorem global_decompress_involutive
    (state : State Input Output Phase Workspace) :
    globalDecompress (globalDecompress state) = state := by
  unfold globalDecompress
  exact decompress_list_involutive _ state

/--
End-to-end finite oracle-to-database bridge for an actual compressed-oracle
state.

If exact CMS simulation maps `compressedState` to a purified total-oracle
family, then uniform-random-oracle claim success is bounded by measured
compressed-database claim success plus the explicit conservative finite loss
`k / sqrt(|Y|)`.
-/
theorem compressed_oracle_claims_amplitude_bridge_weighted
    (compressedState : State Input Output Phase Workspace)
    (family : OracleRegisterFamily
      (Input := Input) (Output := Output) (Phase := Phase)
      (Workspace := Workspace))
    (simulation :
      globalDecompress compressedState = totalOracleFamilyState family)
    (claims : List (Input × Output))
    (distinctInputs : (claims.map Prod.fst).Nodup) :
    Real.sqrt
        (normSquared
          (databaseEventProjection (ClaimsDatabaseEvent claims)
            (totalOracleFamilyState family))) ≤
      Real.sqrt
          (normSquared
            (databaseEventProjection (ClaimsDatabaseEvent claims)
              compressedState)) +
        claims.length *
          Real.sqrt
            ((1 / (Fintype.card Output : ℝ)) *
              normSquared compressedState) := by
  let standardState := globalDecompress compressedState
  have standardTotal :
      ∀ claim ∈ claims, TotalAt claim.1 standardState := by
    intro claim _
    change TotalAt claim.1 (globalDecompress compressedState)
    rw [simulation]
    exact total_oracle_family_state_total_at family claim.1
  have standardNorm :
      normSquared standardState = normSquared compressedState := by
    exact decompress_list_preserves_norm_squared
      (Finset.univ : Finset Input).toList compressedState
  have bridge :=
    event_probability_decompression_amplitude_le
      (ClaimsDatabaseEvent claims) claims standardState distinctInputs
      (fun claim member database records => records claim member)
      standardTotal
  have selectedEqualsCompressed :
      normSquared
          (databaseEventProjection (ClaimsDatabaseEvent claims)
            (decompressList (claims.map Prod.fst) standardState)) =
        normSquared
          (databaseEventProjection (ClaimsDatabaseEvent claims)
            compressedState) := by
    rw [← claims_event_projection_norm_global_decompress_eq_selected
      claims standardState distinctInputs]
    simp only [standardState, global_decompress_involutive]
  calc
    Real.sqrt
        (normSquared
          (databaseEventProjection (ClaimsDatabaseEvent claims)
            (totalOracleFamilyState family))) =
      Real.sqrt
        (normSquared
          (databaseEventProjection (ClaimsDatabaseEvent claims)
            standardState)) := by
      simp only [standardState, simulation]
    _ ≤
      Real.sqrt
          (normSquared
            (databaseEventProjection (ClaimsDatabaseEvent claims)
              (decompressList (claims.map Prod.fst) standardState))) +
        claims.length *
          Real.sqrt
            ((1 / (Fintype.card Output : ℝ)) *
              normSquared standardState) :=
      bridge
    _ =
      Real.sqrt
          (normSquared
            (databaseEventProjection (ClaimsDatabaseEvent claims)
              compressedState)) +
        claims.length *
          Real.sqrt
            ((1 / (Fintype.card Output : ℝ)) *
              normSquared compressedState) := by
      rw [selectedEqualsCompressed, standardNorm]

theorem compressed_oracle_claims_amplitude_bridge
    (compressedState : State Input Output Phase Workspace)
    (family : OracleRegisterFamily
      (Input := Input) (Output := Output) (Phase := Phase)
      (Workspace := Workspace))
    (simulation :
      globalDecompress compressedState = totalOracleFamilyState family)
    (claims : List (Input × Output))
    (distinctInputs : (claims.map Prod.fst).Nodup)
    (normalized : normSquared compressedState ≤ 1) :
    Real.sqrt
        (normSquared
          (databaseEventProjection (ClaimsDatabaseEvent claims)
            (totalOracleFamilyState family))) ≤
      Real.sqrt
          (normSquared
            (databaseEventProjection (ClaimsDatabaseEvent claims)
              compressedState)) +
        claims.length *
          Real.sqrt (1 / (Fintype.card Output : ℝ)) := by
  let standardState := globalDecompress compressedState
  have standardNormalized : normSquared standardState ≤ 1 := by
    simpa [standardState, globalDecompress] using
      (show
        normSquared
            (decompressList (Finset.univ : Finset Input).toList
              compressedState) ≤ 1 from
          (decompress_list_preserves_norm_squared
            (Finset.univ : Finset Input).toList compressedState).le.trans
              normalized)
  have standardTotal :
      ∀ claim ∈ claims, TotalAt claim.1 standardState := by
    intro claim _
    change TotalAt claim.1 (globalDecompress compressedState)
    rw [simulation]
    exact total_oracle_family_state_total_at family claim.1
  have bridge :=
    normalized_event_probability_decompression_amplitude_le
      (ClaimsDatabaseEvent claims) claims standardState distinctInputs
      (fun claim member database records => records claim member)
      standardTotal standardNormalized
  have selectedEqualsCompressed :
      normSquared
          (databaseEventProjection (ClaimsDatabaseEvent claims)
            (decompressList (claims.map Prod.fst) standardState)) =
        normSquared
          (databaseEventProjection (ClaimsDatabaseEvent claims)
            compressedState) := by
    rw [← claims_event_projection_norm_global_decompress_eq_selected
      claims standardState distinctInputs]
    simp only [standardState, global_decompress_involutive]
  calc
    Real.sqrt
        (normSquared
          (databaseEventProjection (ClaimsDatabaseEvent claims)
            (totalOracleFamilyState family))) =
      Real.sqrt
        (normSquared
          (databaseEventProjection (ClaimsDatabaseEvent claims)
            standardState)) := by
      simp only [standardState, simulation]
    _ ≤
      Real.sqrt
          (normSquared
            (databaseEventProjection (ClaimsDatabaseEvent claims)
              (decompressList (claims.map Prod.fst) standardState))) +
        claims.length *
          Real.sqrt (1 / (Fintype.card Output : ℝ)) :=
      bridge
    _ =
      Real.sqrt
          (normSquared
            (databaseEventProjection (ClaimsDatabaseEvent claims)
              compressedState)) +
        claims.length *
          Real.sqrt (1 / (Fintype.card Output : ℝ)) := by
      rw [selectedEqualsCompressed]

end StateLevelBridge

section MultiCoordinateRow

/-- Recorded-to-recorded matrix coefficient of one decompression coordinate. -/
def recordedRowCoefficient
    (target source : Output) : ℝ :=
  (if source = target then 1 else 0) -
    1 / (Fintype.card Output : ℝ)

@[simp]
theorem recorded_row_coefficient_self
    (target : Output) :
    recordedRowCoefficient target target =
      1 - 1 / (Fintype.card Output : ℝ) := by
  simp [recordedRowCoefficient]

/-- Exact squared norm of one recorded row of the decompression reflection. -/
theorem sum_recorded_row_coefficient_sq
    (target : Output) :
    (∑ source : Output,
      recordedRowCoefficient target source ^ 2) =
        1 - 1 / (Fintype.card Output : ℝ) := by
  let card : ℝ := Fintype.card Output
  have cardPositive : 0 < card := by
    dsimp [card]
    exact_mod_cast Fintype.card_pos (α := Output)
  calc
    (∑ source : Output,
      recordedRowCoefficient target source ^ 2) =
        ∑ source : Output, (
          (if source = target then (1 - 2 / card) else 0) +
            (1 / card) ^ 2) := by
      apply Finset.sum_congr rfl
      intro source _
      by_cases same : source = target
      · subst source
        simp [recordedRowCoefficient, card]
        ring
      · simp [recordedRowCoefficient, card, same]
    _ = 1 - 1 / card := by
      have indicatorSum :
          (∑ source : Output,
            if source = target then (1 - 2 / card) else 0) =
            1 - 2 / card := by
        simp
      have constantSum :
          (∑ _source : Output, (1 / card) ^ 2) =
            (Fintype.card Output : ℝ) * (1 / card) ^ 2 := by
        simp
      rw [Finset.sum_add_distrib, indicatorSum, constantSum]
      change
        1 - 2 / card + card * (1 / card) ^ 2 =
          1 - 1 / card
      field_simp
      ring
    _ = 1 - 1 / (Fintype.card Output : ℝ) := by
      rfl

/-- Tensor-product row coefficient for several distinct claimed oracle inputs. -/
def recordedTupleRowCoefficient
    {arity : Nat}
    (target source : Fin arity → Output) : ℝ :=
  ∏ coordinate,
    recordedRowCoefficient (target coordinate) (source coordinate)

@[simp]
theorem recorded_tuple_row_coefficient_self
    {arity : Nat}
    (target : Fin arity → Output) :
    recordedTupleRowCoefficient target target =
      (1 - 1 / (Fintype.card Output : ℝ)) ^ arity := by
  simp [recordedTupleRowCoefficient]

/-- Exact squared norm of a tensor-product recorded row. -/
theorem sum_recorded_tuple_row_coefficient_sq
    {arity : Nat}
    (target : Fin arity → Output) :
    (∑ source : Fin arity → Output,
      recordedTupleRowCoefficient target source ^ 2) =
        (1 - 1 / (Fintype.card Output : ℝ)) ^ arity := by
  calc
    (∑ source : Fin arity → Output,
      recordedTupleRowCoefficient target source ^ 2) =
        ∑ source : Fin arity → Output,
          ∏ coordinate,
            recordedRowCoefficient
              (target coordinate) (source coordinate) ^ 2 := by
      apply Finset.sum_congr rfl
      intro source _
      simp [recordedTupleRowCoefficient, Finset.prod_pow]
    _ =
        ∏ coordinate : Fin arity,
          ∑ source : Output,
            recordedRowCoefficient (target coordinate) source ^ 2 := by
      exact (Fintype.prod_sum
        (fun coordinate source =>
          recordedRowCoefficient (target coordinate) source ^ 2)).symm
    _ =
        ∏ _coordinate : Fin arity,
          (1 - 1 / (Fintype.card Output : ℝ)) := by
      apply Finset.prod_congr rfl
      intro coordinate _
      exact sum_recorded_row_coefficient_sq (target coordinate)
    _ = (1 - 1 / (Fintype.card Output : ℝ)) ^ arity := by
      simp

/-- Difference between the ideal consistency row and the measured-database row. -/
def bridgeTupleRowCoefficient
    {arity : Nat}
    (target source : Fin arity → Output) : ℝ :=
  (if source = target then 1 else 0) -
    recordedTupleRowCoefficient target source

/-- Exact squared norm of the multi-claim bridge row. -/
theorem sum_bridge_tuple_row_coefficient_sq
    {arity : Nat}
    (target : Fin arity → Output) :
    (∑ source : Fin arity → Output,
      bridgeTupleRowCoefficient target source ^ 2) =
        1 - (1 - 1 / (Fintype.card Output : ℝ)) ^ arity := by
  calc
    (∑ source : Fin arity → Output,
      bridgeTupleRowCoefficient target source ^ 2) =
        ∑ source : Fin arity → Output, (
          (if source = target then 1 else 0) +
            recordedTupleRowCoefficient target source ^ 2 -
            2 * (if source = target then
              recordedTupleRowCoefficient target source else 0)) := by
      apply Finset.sum_congr rfl
      intro source _
      by_cases same : source = target
      · simp [bridgeTupleRowCoefficient, same]
        ring
      · simp [bridgeTupleRowCoefficient, same]
    _ =
        1 +
          (1 - 1 / (Fintype.card Output : ℝ)) ^ arity -
          2 * (1 - 1 / (Fintype.card Output : ℝ)) ^ arity := by
      rw [Finset.sum_sub_distrib, Finset.sum_add_distrib,
        sum_recorded_tuple_row_coefficient_sq]
      simp [recorded_tuple_row_coefficient_self]
    _ = 1 - (1 - 1 / (Fintype.card Output : ℝ)) ^ arity := by
      ring

/-- Finite union/Bernoulli bound, proved without asymptotics. -/
theorem one_sub_one_sub_pow_le
    (probability : ℝ)
    (nonnegative : 0 ≤ probability)
    (atMostOne : probability ≤ 1)
    (arity : Nat) :
    1 - (1 - probability) ^ arity ≤ arity * probability := by
  induction arity with
  | zero =>
      simp
  | succ arity inductionHypothesis =>
      have complementNonnegative : 0 ≤ 1 - probability := by
        linarith
      have complementAtMostOne : 1 - probability ≤ 1 := by
        linarith
      have powerAtMostOne :
          (1 - probability) ^ arity ≤ 1 :=
        pow_le_one₀ complementNonnegative complementAtMostOne
      calc
        1 - (1 - probability) ^ (arity + 1) =
            (1 - (1 - probability) ^ arity) +
              probability * (1 - probability) ^ arity := by
          rw [pow_succ]
          ring
        _ ≤ arity * probability +
              probability * (1 - probability) ^ arity := by
          exact add_le_add_left inductionHypothesis _
        _ ≤ arity * probability + probability := by
          exact add_le_add_right
            (mul_le_of_le_one_right nonnegative powerAtMostOne) _
        _ = ((arity : ℝ) + 1) * probability := by
          ring
        _ = ((arity + 1 : Nat) : ℝ) * probability := by
          norm_num

/-- Exact bridge-row norm is bounded by the published `k / |Y|` loss. -/
theorem sum_bridge_tuple_row_coefficient_sq_le
    {arity : Nat}
    (target : Fin arity → Output) :
    (∑ source : Fin arity → Output,
      bridgeTupleRowCoefficient target source ^ 2) ≤
        (arity : ℝ) / Fintype.card Output := by
  have cardPositive : (0 : ℝ) < Fintype.card Output :=
    output_card_real_positive (Output := Output)
  have cardAtLeastOne : (1 : ℝ) ≤ Fintype.card Output := by
    exact_mod_cast Fintype.card_pos (α := Output)
  have inverseNonnegative :
      0 ≤ (1 : ℝ) / Fintype.card Output := by
    positivity
  have inverseAtMostOne :
      (1 : ℝ) / Fintype.card Output ≤ 1 := by
    exact (div_le_one cardPositive).2 cardAtLeastOne
  rw [sum_bridge_tuple_row_coefficient_sq]
  simpa [Nat.cast_ofNat, div_eq_mul_inv] using
    one_sub_one_sub_pow_le
      ((1 : ℝ) / Fintype.card Output)
      inverseNonnegative inverseAtMostOne arity

/-- Measured-database amplitude obtained from a total-oracle tuple fiber. -/
def recordedTupleAmplitude
    {arity : Nat}
    (target : Fin arity → Output)
    (coefficient : (Fin arity → Output) → ℂ) : ℂ :=
  ∑ source : Fin arity → Output,
    coefficient source *
      (recordedTupleRowCoefficient target source : ℂ)

/-- Exact expansion of the ideal-minus-recorded amplitude through the bridge row. -/
theorem ideal_sub_recorded_tuple_amplitude
    {arity : Nat}
    (target : Fin arity → Output)
    (coefficient : (Fin arity → Output) → ℂ) :
    coefficient target - recordedTupleAmplitude target coefficient =
      ∑ source : Fin arity → Output,
        coefficient source *
          (bridgeTupleRowCoefficient target source : ℂ) := by
  unfold recordedTupleAmplitude bridgeTupleRowCoefficient
  have single :
      (∑ source : Fin arity → Output,
        coefficient source *
          ((if source = target then 1 else 0) : ℂ)) =
        coefficient target := by
    simp
  calc
    coefficient target -
        ∑ source, coefficient source *
          (recordedTupleRowCoefficient target source : ℂ) =
      (∑ source, coefficient source *
          ((if source = target then 1 else 0) : ℂ)) -
        ∑ source, coefficient source *
          (recordedTupleRowCoefficient target source : ℂ) := by
      rw [single]
    _ =
      ∑ source,
        (coefficient source *
            ((if source = target then 1 else 0) : ℂ) -
          coefficient source *
            (recordedTupleRowCoefficient target source : ℂ)) := by
      rw [Finset.sum_sub_distrib]
    _ =
      ∑ source,
        coefficient source *
          (bridgeTupleRowCoefficient target source : ℂ) := by
      apply Finset.sum_congr rfl
      intro source _
      by_cases same : source = target
      · simp [bridgeTupleRowCoefficient, same]
        ring
      · simp [bridgeTupleRowCoefficient, same]

/--
State-level multi-claim bridge for the concrete decompression row.  No Fourier-basis
assumption remains: the result follows from the exact implemented Householder matrix.
-/
theorem ideal_sub_recorded_tuple_amplitude_normSq_le
    {arity : Nat}
    (target : Fin arity → Output)
    (coefficient : (Fin arity → Output) → ℂ) :
    Complex.normSq
        (coefficient target -
          recordedTupleAmplitude target coefficient) ≤
      ((arity : ℝ) / Fintype.card Output) *
        ∑ source : Fin arity → Output,
          Complex.normSq (coefficient source) := by
  rw [ideal_sub_recorded_tuple_amplitude]
  have cauchy :=
    normSq_sum_mul_le_sum_normSq_mul_sum_normSq
      (Finset.univ : Finset (Fin arity → Output))
      coefficient
      (fun source => (bridgeTupleRowCoefficient target source : ℂ))
  calc
    Complex.normSq
        (∑ source : Fin arity → Output,
          coefficient source *
            (bridgeTupleRowCoefficient target source : ℂ)) ≤
      (∑ source : Fin arity → Output,
          Complex.normSq (coefficient source)) *
        ∑ source : Fin arity → Output,
          Complex.normSq
            (bridgeTupleRowCoefficient target source : ℂ) :=
      cauchy
    _ =
      (∑ source : Fin arity → Output,
          Complex.normSq (coefficient source)) *
        ∑ source : Fin arity → Output,
          bridgeTupleRowCoefficient target source ^ 2 := by
      congr 1
      apply Finset.sum_congr rfl
      intro source _
      rw [Complex.normSq_ofReal]
      ring
    _ ≤
      (∑ source : Fin arity → Output,
          Complex.normSq (coefficient source)) *
        ((arity : ℝ) / Fintype.card Output) := by
      apply mul_le_mul_of_nonneg_left
      · exact sum_bridge_tuple_row_coefficient_sq_le target
      · exact Finset.sum_nonneg fun source _ =>
          Complex.normSq_nonneg (coefficient source)
    _ =
      ((arity : ℝ) / Fintype.card Output) *
        ∑ source : Fin arity → Output,
          Complex.normSq (coefficient source) := by
      ring

@[simp]
theorem decompress_kernel_some_some
    (source target : Output) :
    HegemonCrypto.CmsOracleSimulation.decompressKernel
        (Output := Output) (some source) (some target) =
      (recordedRowCoefficient target source : ℂ) := by
  unfold HegemonCrypto.CmsOracleSimulation.decompressKernel
    recordedRowCoefficient
  rw [decompress_recorded_ket_apply_some]
  unfold inverseOutputCard
  by_cases same : source = target
  · subst source
    simp
  · simp [same, Ne.symm same]

/-- Matrix coefficient of decompression over all selected claim coordinates. -/
def selectedDecompressionKernel
    {arity : Nat}
    (target source : Fin arity → Output) : ℂ :=
  ∏ coordinate,
    HegemonCrypto.CmsOracleSimulation.decompressKernel
      (Output := Output)
      (some (source coordinate))
      (some (target coordinate))

/-- The concrete selected-coordinate kernel is exactly the real row used above. -/
theorem selected_decompression_kernel_eq_recorded_row
    {arity : Nat}
    (target source : Fin arity → Output) :
    selectedDecompressionKernel target source =
      (recordedTupleRowCoefficient target source : ℂ) := by
  unfold selectedDecompressionKernel recordedTupleRowCoefficient
  simp_rw [decompress_kernel_some_some]
  exact
    (Complex.ofReal_prod (Finset.univ : Finset (Fin arity))
      (fun coordinate =>
        recordedRowCoefficient
          (target coordinate) (source coordinate))).symm

/-- The abstract recorded amplitude is the exact selected-coordinate decompression matrix. -/
theorem recorded_tuple_amplitude_eq_selected_decompression
    {arity : Nat}
    (target : Fin arity → Output)
    (coefficient : (Fin arity → Output) → ℂ) :
    recordedTupleAmplitude target coefficient =
      ∑ source : Fin arity → Output,
        coefficient source * selectedDecompressionKernel target source := by
  unfold recordedTupleAmplitude
  simp_rw [selected_decompression_kernel_eq_recorded_row]

end MultiCoordinateRow

end ConcreteDecompression

end

end HegemonCrypto.CmsOracleDatabaseBridge
