import HegemonCrypto.SmallWoodV8Smz9DecsDegreeEnforcement
import HegemonCrypto.SmallWoodV8Smz9AdmissibleRootProbability

/-!
# SMZ9 accumulated-support selection: obstruction and a bounded-family repair

The current fixed-oracle DECS theorem charges `p^-5`.  Its residual must be fixed before the
uniform five-by-140 matrix.  Interpolating an accepted support chosen after that matrix need not
preserve this quantifier order.  This module proves that selecting between only two nonzero
coordinate residuals already gives probability strictly greater than `p^-5`.

It also proves the sound replacement for a fixed finite family: an arbitrary matrix-dependent
selector incurs at most `family.card * p^-5`.  The family, its residuals, and its affine targets
are fixed theorem arguments; bounding the family generated by an executable accepted-rewind
extractor, and transferring its experiment through quantum measurement, are not proved here.

A degree-387 polynomial cannot represent an indicator word on a support with at least 389
distinct actual SMZ9 coset points.  This is the source-exact algebraic obstruction used by the
two-indicator-row counterexample documented in `docs/crypto/smz9-campaign/soundness-argument.md`.
These are obstruction/selection theorems, not complete-verifier forgery or soundness claims.
-/

namespace HegemonCrypto.SmallWood.V8Smz9AccumulatedExtraction

open Polynomial
open HegemonCrypto.SmallWoodPowerBatching
open V8Smz9OracleExtraction
open DecsExtraction

noncomputable section

set_option maxHeartbeats 1000000
set_option maxRecDepth 5000

local instance : NeZero V8Smz9LogicalOracle.decsRowCount := ⟨by decide⟩
local instance : NeZero V8Smz9LogicalOracle.decsEta := ⟨by decide⟩

abbrev Smz9Matrix := CoefficientMatrix (F := Goldilocks)
  V8Smz9LogicalOracle.decsRowCount V8Smz9LogicalOracle.decsEta

namespace CoordinateEvents

variable {F Row Column : Type*} [Field F] [Fintype F] [DecidableEq F]
  [Fintype Row] [DecidableEq Row] [Fintype Column] [DecidableEq Column]

def failure (coordinate : Column) : Finset (Row → Column → F) :=
  Finset.univ.filter fun matrix => ∀ row, matrix row coordinate = 0

theorem mem_failure (coordinate : Column) (matrix : Row → Column → F) :
    matrix ∈ failure coordinate ↔ ∀ row, matrix row coordinate = 0 := by
  simp only [failure, Finset.mem_filter, Finset.mem_univ, true_and]

def combined (left right : Column) : Finset (Row → Column → F) :=
  failure left ∪ failure right

theorem mem_union (left right : Column) (matrix : Row → Column → F) :
    matrix ∈ combined left right ↔
      (∀ row, matrix row left = 0) ∨ (∀ row, matrix row right = 0) := by
  simp only [combined, Finset.mem_union, mem_failure]

theorem strict_union (left right : Column) (different : left ≠ right) (oneRow : Row) :
    failure (F := F) (Row := Row) left ⊂ failure left ∪ failure right := by
  let separator : Row → Column → F := fun _ column => if column = left then 1 else 0
  have secondMember : separator ∈ failure right := by
    rw [mem_failure]
    intro row
    exact if_neg different.symm
  have notFirst : separator ∉ failure left := by
    intro member
    have impossible := (mem_failure left separator).mp member oneRow
    change (if left = left then (1 : F) else 0) = 0 at impossible
    rw [if_pos rfl] at impossible
    exact one_ne_zero impossible
  apply Finset.ssubset_iff_subset_ne.mpr
  refine ⟨Finset.subset_union_left, ?_⟩
  intro same
  apply notFirst
  rw [same]
  exact Finset.mem_union.mpr (Or.inr secondMember)

end CoordinateEvents

def coordinateResidual (coordinate : Fin V8Smz9LogicalOracle.decsRowCount) :
    Fin V8Smz9LogicalOracle.decsRowCount → Goldilocks :=
  fun index => if index = coordinate then 1 else 0

theorem coordinate_residual_nonzero (coordinate : Fin V8Smz9LogicalOracle.decsRowCount) :
    ∃ index, coordinateResidual coordinate index ≠ 0 := by
  exact ⟨coordinate, by simp [coordinateResidual]⟩

theorem coordinate_residual_dot
    (coordinate : Fin V8Smz9LogicalOracle.decsRowCount)
    (coefficients : Fin V8Smz9LogicalOracle.decsRowCount → Goldilocks) :
    uniformDotProduct (coordinateResidual coordinate) coefficients = coefficients coordinate := by
  simp [uniformDotProduct, coordinateResidual]

abbrev coordinateFailureSet : Fin V8Smz9LogicalOracle.decsRowCount → Finset Smz9Matrix :=
  CoordinateEvents.failure

theorem mem_coordinate_failure_set
    (coordinate : Fin V8Smz9LogicalOracle.decsRowCount) (matrix : Smz9Matrix) :
    matrix ∈ coordinateFailureSet coordinate ↔ ∀ row, matrix row coordinate = 0 := by
  exact CoordinateEvents.mem_failure coordinate matrix

def matrixEventProbability (event : Finset Smz9Matrix) : Rat :=
  event.card / Fintype.card Smz9Matrix

theorem coordinate_failure_probability_exact
    (coordinate : Fin V8Smz9LogicalOracle.decsRowCount) :
    matrixEventProbability (coordinateFailureSet coordinate) =
      ((1 : Rat) / Fintype.card Goldilocks) ^ 5 := by
  have eventEq : coordinateFailureSet coordinate =
      uniformMatrixFailureSet (coordinateResidual coordinate) V8Smz9LogicalOracle.decsEta := by
    ext matrix
    simp [coordinateFailureSet, CoordinateEvents.failure,
      uniformMatrixFailureSet, Fintype.mem_piFinset,
      uniformDotZeroSet, coordinate_residual_dot]
  unfold matrixEventProbability
  rw [eventEq]
  change uniformMatrixFailureProbability (coordinateResidual coordinate)
    V8Smz9LogicalOracle.decsEta = _
  rw [uniform_matrix_failure_probability_eq_independent,
    independent_uniform_matrix_failure_probability_exact (coordinate_residual_nonzero coordinate)]
  rfl

/-- Selecting either of two candidate supports corresponds to a union, not one fixed fiber. -/
def twoCandidateFailureSet : Finset Smz9Matrix :=
  CoordinateEvents.combined (F := Goldilocks)
    (Row := Fin V8Smz9LogicalOracle.decsEta)
    (Column := Fin V8Smz9LogicalOracle.decsRowCount) 0 1

theorem mem_two_candidate_failure_set (matrix : Smz9Matrix) :
    matrix ∈ twoCandidateFailureSet ↔
      (∀ row, matrix row 0 = 0) ∨ (∀ row, matrix row 1 = 0) :=
  CoordinateEvents.mem_union 0 1 matrix

/-- One explicit matrix lies in the second event but not the first. -/
def separatesCandidateFailures : Smz9Matrix :=
  fun _ coordinate => if coordinate = 0 then 1 else 0

theorem first_candidate_failure_is_strict_subset :
    coordinateFailureSet 0 ⊂ twoCandidateFailureSet := by
  exact CoordinateEvents.strict_union 0 1 (by decide)
    (⟨0, by decide⟩ : Fin V8Smz9LogicalOracle.decsEta)

/-- A kernel-checked counterexample to replacing a selected residual by a fixed residual. -/
theorem adaptive_two_candidate_probability_exceeds_fixed_oracle_bound :
    ((1 : Rat) / Fintype.card Goldilocks) ^ 5 <
      matrixEventProbability twoCandidateFailureSet := by
  rw [← coordinate_failure_probability_exact 0]
  unfold matrixEventProbability
  apply (div_lt_div_iff_of_pos_right (by exact_mod_cast Fintype.card_pos (α := Smz9Matrix))).mpr
  exact_mod_cast Finset.card_lt_card first_candidate_failure_is_strict_subset

section FixedFamily

variable {Candidate : Type*} [Fintype Candidate] [DecidableEq Candidate]

/-- The selector may depend arbitrarily on the matrix, but the candidate family is fixed. -/
def selectedAffineResidualFailureSet
    (residual : Candidate → Fin V8Smz9LogicalOracle.decsRowCount → Goldilocks)
    (target : Candidate → Fin V8Smz9LogicalOracle.decsEta → Goldilocks)
    (select : Smz9Matrix → Candidate) : Finset Smz9Matrix :=
  Finset.univ.filter fun matrix => matrix ∈
    uniformAffineMatrixFailureSet (residual (select matrix)) (target (select matrix))

private theorem selected_event_subset_union
    {Element Index : Type*} [Fintype Element] [DecidableEq Element]
    [Fintype Index] [DecidableEq Index]
    (events : Index → Finset Element) (select : Element → Index) :
    (Finset.univ.filter fun element => element ∈ events (select element)) ⊆
      Finset.univ.biUnion events := by
  intro element member
  exact Finset.mem_biUnion.mpr
    ⟨select element, Finset.mem_univ _, (Finset.mem_filter.mp member).2⟩

theorem selected_affine_residual_failure_subset_family
    (residual : Candidate → Fin V8Smz9LogicalOracle.decsRowCount → Goldilocks)
    (target : Candidate → Fin V8Smz9LogicalOracle.decsEta → Goldilocks)
    (select : Smz9Matrix → Candidate) :
    selectedAffineResidualFailureSet residual target select ⊆
      affineResidualFamilyFailureSet residual target := by
  exact selected_event_subset_union
    (fun candidate => uniformAffineMatrixFailureSet (residual candidate) (target candidate)) select

/-- Sound adaptivity charge for an arbitrary selector from a fixed family of nonzero residuals. -/
theorem selected_affine_residual_failure_probability_le
    (residual : Candidate → Fin V8Smz9LogicalOracle.decsRowCount → Goldilocks)
    (target : Candidate → Fin V8Smz9LogicalOracle.decsEta → Goldilocks)
    (select : Smz9Matrix → Candidate)
    (allNonzero : ∀ candidate, ∃ coordinate, residual candidate coordinate ≠ 0) :
    matrixEventProbability (selectedAffineResidualFailureSet residual target select) ≤
      Fintype.card Candidate * (((1 : Rat) / Fintype.card Goldilocks) ^ 5) := by
  apply le_trans _ (affine_residual_family_failure_probability_le residual target allNonzero)
  unfold matrixEventProbability affineResidualFamilyFailureProbability
  apply div_le_div_of_nonneg_right _ (Nat.cast_nonneg _)
  exact_mod_cast Finset.card_le_card
    (selected_affine_residual_failure_subset_family residual target select)

end FixedFamily

/-- One fixed indicator word on the actual `2^23`-point SMZ9 coset. -/
def indicatorWord (special : Fin decsDomainSize) : Fin decsDomainSize → Goldilocks :=
  fun coordinate => if coordinate = special then 1 else 0

/-- A 389-point support containing the spike has no degree-387 completion. -/
theorem indicator_word_not_degree_bounded_on_large_support
    (special : Fin decsDomainSize)
    (support : Finset (Fin decsDomainSize))
    (containsSpecial : special ∈ support)
    (largeSupport : V8Smz9QromAccounting.decsPolynomialDegree + 2 ≤ support.card) :
    ¬ IsDegreeBoundedWord support smz9EvaluationPoint (indicatorWord special)
      V8Smz9QromAccounting.decsPolynomialDegree := by
  rintro ⟨polynomial, degreeBound, agrees⟩
  have nonzero : polynomial ≠ 0 := by
    intro zeroPolynomial
    have atSpecial := agrees special containsSpecial
    simp [zeroPolynomial, indicatorWord] at atSpecial
  let embedding : { coordinate // coordinate ∈ support.erase special } ↪
      { point // point ∈ FiniteFieldSampling.rootSet polynomial } :=
    { toFun := fun coordinate =>
        ⟨smz9EvaluationPoint coordinate.val,
          (FiniteFieldSampling.mem_root_set_iff polynomial _).mpr (by
            rw [agrees coordinate.val (Finset.mem_of_mem_erase coordinate.property)]
            exact if_neg (Finset.ne_of_mem_erase coordinate.property))⟩
      inj' := by
        intro left right same
        apply Subtype.ext
        apply smz9_evaluation_point_injective
        exact congrArg
          (fun point : { point // point ∈ FiniteFieldSampling.rootSet polynomial } => point.val)
          same }
  have rootCount : (support.erase special).card ≤ polynomial.natDegree := by
    have subsetCount : (support.erase special).card ≤
        (FiniteFieldSampling.rootSet polynomial).card := by
      simpa only [Fintype.card_coe] using Fintype.card_le_of_embedding embedding
    exact subsetCount.trans (FiniteFieldSampling.root_set_card_le_nat_degree nonzero)
  rw [Finset.card_erase_of_mem containsSpecial] at rootCount
  omega

local instance : NeZero decsDomainSize := ⟨by decide⟩

/-- Fixed field-valued data rows in exactly the current 140-row source layout; masks are zero. -/
def fixedIndicatorData (column : Fin V8Smz9LogicalOracle.decsRowCount)
    (coordinate : Fin decsDomainSize) : Goldilocks :=
  (if column = 0 then indicatorWord 0 coordinate else 0) +
    (if column = 1 then indicatorWord 1 coordinate else 0)

theorem fixed_indicator_data_zero : fixedIndicatorData 0 = indicatorWord 0 := by
  funext coordinate
  have different : (0 : Fin V8Smz9LogicalOracle.decsRowCount) ≠ 1 := by decide
  simp only [fixedIndicatorData, if_neg different, add_zero, ite_true]

theorem fixed_indicator_data_one : fixedIndicatorData 1 = indicatorWord 1 := by
  funext coordinate
  have different : (1 : Fin V8Smz9LogicalOracle.decsRowCount) ≠ 0 := by decide
  simp only [fixedIndicatorData, if_neg different, zero_add, ite_true]

theorem fixed_indicator_response_eq (matrix : Smz9Matrix)
    (row : Fin V8Smz9LogicalOracle.decsEta) (coordinate : Fin decsDomainSize) :
    (∑ column, matrix row column * fixedIndicatorData column coordinate) =
      matrix row 0 * indicatorWord 0 coordinate + matrix row 1 * indicatorWord 1 coordinate := by
  simp [fixedIndicatorData, mul_add, Finset.sum_add_distrib]

/-- The source stays fixed; only the accumulated support is selected after seeing the matrix. -/
def selectedIndicatorSupport (matrix : Smz9Matrix) : Finset (Fin decsDomainSize) :=
  if ∀ row, matrix row 0 = 0 then Finset.univ.erase 1
  else if ∀ row, matrix row 1 = 0 then Finset.univ.erase 0
  else (Finset.univ.erase 0).erase 1

/-- Every selected row satisfies the same zero response, for every challenge matrix. -/
theorem selected_indicator_support_matches_zero_response
    (matrix : Smz9Matrix) (row : Fin V8Smz9LogicalOracle.decsEta)
    (coordinate : Fin decsDomainSize)
    (member : coordinate ∈ selectedIndicatorSupport matrix) :
    (∑ column, matrix row column * fixedIndicatorData column coordinate) = 0 := by
  rw [fixed_indicator_response_eq]
  unfold selectedIndicatorSupport at member
  split_ifs at member with first second
  · rw [first row, zero_mul, zero_add]
    have different := Finset.ne_of_mem_erase member
    simp only [indicatorWord, if_neg different, mul_zero]
  · rw [second row, zero_mul, add_zero]
    have different := Finset.ne_of_mem_erase member
    simp only [indicatorWord, if_neg different, mul_zero]
  · have differentOne := Finset.ne_of_mem_erase member
    have differentZero := Finset.ne_of_mem_erase (Finset.mem_of_mem_erase member)
    simp only [indicatorWord, if_neg differentZero, if_neg differentOne, mul_zero, zero_add]

set_option linter.constructorNameAsVariable false in
/-- Either candidate event forces a selected data row outside degree 387 on that very support. -/
theorem selected_indicator_support_has_noncodeword_on_union
    (matrix : Smz9Matrix) (event : matrix ∈ twoCandidateFailureSet) :
    ∃ column : Fin V8Smz9LogicalOracle.decsRowCount,
      ¬ IsDegreeBoundedWord (selectedIndicatorSupport matrix) smz9EvaluationPoint
        (fixedIndicatorData column) V8Smz9QromAccounting.decsPolynomialDegree := by
  rw [mem_two_candidate_failure_set] at event
  have unionEvent := event
  by_cases first : ∀ row, matrix row 0 = 0
  · refine ⟨0, ?_⟩
    rw [fixed_indicator_data_zero]
    unfold selectedIndicatorSupport
    rw [if_pos first]
    apply indicator_word_not_degree_bounded_on_large_support
    · exact Finset.mem_erase.mpr ⟨by decide, Finset.mem_univ _⟩
    · rw [Finset.card_erase_of_mem (Finset.mem_univ _), Finset.card_univ, Fintype.card_fin]
      decide
  · have second := unionEvent.resolve_left first
    refine ⟨1, ?_⟩
    rw [fixed_indicator_data_one]
    unfold selectedIndicatorSupport
    rw [if_neg first, if_pos second]
    apply indicator_word_not_degree_bounded_on_large_support
    · exact Finset.mem_erase.mpr ⟨by decide, Finset.mem_univ _⟩
    · rw [Finset.card_erase_of_mem (Finset.mem_univ _), Finset.card_univ, Fintype.card_fin]
      decide

/-- Connected obstruction: one fixed source and zero response, adaptive accepted supports,
and a bad-support event whose probability is strictly larger than the fixed-oracle term. -/
theorem fixed_source_selected_support_obstruction :
    (∀ matrix row coordinate, coordinate ∈ selectedIndicatorSupport matrix →
      (∑ column, matrix row column * fixedIndicatorData column coordinate) = 0) ∧
    (∀ matrix, matrix ∈ twoCandidateFailureSet →
      ∃ column : Fin V8Smz9LogicalOracle.decsRowCount,
        ¬ IsDegreeBoundedWord (selectedIndicatorSupport matrix) smz9EvaluationPoint
          (fixedIndicatorData column) V8Smz9QromAccounting.decsPolynomialDegree) ∧
    ((1 : Rat) / Fintype.card Goldilocks) ^ 5 <
      matrixEventProbability twoCandidateFailureSet := by
  exact ⟨selected_indicator_support_matches_zero_response,
    selected_indicator_support_has_noncodeword_on_union,
    adaptive_two_candidate_probability_exceeds_fixed_oracle_bound⟩

end

end HegemonCrypto.SmallWood.V8Smz9AccumulatedExtraction
