name = "hegemon_crypto"
defaultTargets = ["HegemonCrypto"]

[leanOptions]
autoImplicit = false
warningAsError = true

[[require]]
name = "hegemon_formal"
path = "../lean"

[[require]]
name = "Arklib"
git = "https://github.com/Verified-zkEVM/ArkLib"
rev = "e6d77b18ca1334a91faf4d1ccf9f96d854d58ba4"

[[lean_lib]]
name = "HegemonCrypto"
