import SmzaRp05PcsLvcsMiddle

/-!
# Successful indexed-row execution exposes its exact LVCS reconstruction

The sampled indexes and DECS field points are generated by the existing
opening sampler program. A successful `indexedRowsProgram` execution can only
return rows when `reconstructRowsFromPcsFields` succeeds on those same decoded
PCS fields, opened row scalars, and sampled points.
-/

namespace HegemonCrypto.SmallWood.SmzaRp05IndexedRowsReconstructionExecution

open SmzaRp05ExecutableMerkleVerifier (Program Oracle)
open SmzaRp05PcsWireProjection (DecodedMiddleWire)
open V8SmzaOracleParser (RawDigest)

set_option autoImplicit false

theorem program_bind_success {α β : Type} (oracle : Oracle)
    (program : Program α) (next : α → Program β) (result : β)
    (success : (program.bind next).eval oracle = some result) :
    ∃ value, program.eval oracle = some value ∧
      (next value).eval oracle = some result := by
  rw [Program.eval_bind oracle program next] at success
  cases selected : program.eval oracle with
  | none => simp [selected] at success
  | some value =>
      simp only [selected, Option.bind_some] at success
      exact ⟨value, rfl, success⟩

/-- A successful indexed-row run exposes the sampler's actual points and the
successful wire-connected LVCS reconstruction that produced its returned rows. -/
theorem indexedRows_success_exposes_reconstruction
    (pending : Bool) (hPiop : RawDigest) (wire : DecodedMiddleWire)
    (evalPoints : List Goldilocks) (packingFactor : Nat)
    (widths deltas : List Nat) (beta lvcsCols tailCount totalRows : Nat)
    (oracle : Oracle) (indexedProgram : Program (List Nat × List (List Goldilocks)))
    (indexes : List Nat) (rows : List (List Goldilocks))
    (selected : SmzaRp05PcsLvcsMiddle.indexedRowsProgram pending hPiop wire
      evalPoints packingFactor widths deltas beta lvcsCols tailCount totalRows =
        some indexedProgram)
    (executed : indexedProgram.eval oracle = some (indexes, rows)) :
    ∃ sampler points,
      SmzaRp05DecsPointProjection.openingIndexPointProgram pending hPiop
        wire.pcs evalPoints wire.rowScalars packingFactor widths deltas beta
        lvcsCols tailCount = some sampler ∧
      sampler.eval oracle = some (indexes, points) ∧
      SmzaRp05LvcsWireProjection.reconstructRowsFromPcsFields wire.pcs
        evalPoints points wire.rowScalars packingFactor widths deltas beta
        lvcsCols totalRows tailCount = some rows := by
  cases hsampler : SmzaRp05DecsPointProjection.openingIndexPointProgram pending
      hPiop wire.pcs evalPoints wire.rowScalars packingFactor widths deltas beta
      lvcsCols tailCount with
  | none =>
      simp [SmzaRp05PcsLvcsMiddle.indexedRowsProgram, hsampler] at selected
  | some sampler =>
      have selectedProgram :
          (sampler.bind fun (indexes, points) =>
            Program.done ((SmzaRp05LvcsWireProjection.reconstructRowsFromPcsFields
              wire.pcs evalPoints points wire.rowScalars packingFactor widths
              deltas beta lvcsCols totalRows tailCount).map
                (fun rows => (indexes, rows)))) = indexedProgram := by
        simpa [SmzaRp05PcsLvcsMiddle.indexedRowsProgram, hsampler] using selected
      subst indexedProgram
      obtain ⟨sampled, samplerSuccess, reconstructionSuccess⟩ :=
        program_bind_success oracle sampler
          (fun (sampledIndexes, points) =>
            Program.done ((SmzaRp05LvcsWireProjection.reconstructRowsFromPcsFields
              wire.pcs evalPoints points wire.rowScalars packingFactor widths
              deltas beta lvcsCols totalRows tailCount).map
                (fun sampledRows => (sampledIndexes, sampledRows))))
          (indexes, rows) executed
      rcases sampled with ⟨sampledIndexes, points⟩
      cases hrows : SmzaRp05LvcsWireProjection.reconstructRowsFromPcsFields
          wire.pcs evalPoints points wire.rowScalars packingFactor widths deltas
          beta lvcsCols totalRows tailCount with
      | none => simp [hrows, Program.eval] at reconstructionSuccess
      | some reconstructedRows =>
          simp only [Program.eval, hrows, Option.map_some] at reconstructionSuccess
          have rowsPairEq := Option.some.inj reconstructionSuccess
          have indexesEq : sampledIndexes = indexes :=
            congrArg Prod.fst rowsPairEq
          have rowsEq : reconstructedRows = rows :=
            congrArg Prod.snd rowsPairEq
          subst reconstructedRows
          subst sampledIndexes
          exact ⟨sampler, points, rfl, samplerSuccess, hrows⟩

end HegemonCrypto.SmallWood.SmzaRp05IndexedRowsReconstructionExecution
