import SmzaRp05ExecutableFinalVerifier
import SmzaRp05ExecutableMerklePaths

/-! The final verifier call itself supplies the PIOP-to-FPP parser edge.
These are identities of its actual generated bytes, without a supplied
payload, trace, or independent transcript reconstruction assumption. -/
namespace HegemonCrypto.SmallWood.SmzaRp05CurrentPiopFrameReadback

open HegemonCrypto.CanonicalBytes (Byte encodeLE encodeLE_length)
open SmzaRp05ExecutableFinalVerifier
  (ReconstructedTranscript coefficientBytes finalPayload finalInput)
open SmzaRp05LeafNamespace (Namespace)
open SmzaRp05FilteredDecoderInstability (globalNormalizedPayload globalOnlineNext)

set_option autoImplicit false

private theorem encoded_fields_length
    (words : List SmzaRp05ExecutableChallengeStage.FieldWord) :
    (words.flatMap fun word => encodeLE 8 word.val).length = words.length * 8 := by
  induction words with
  | nil => rfl
  | cons word words ih =>
      simp only [List.flatMap_cons, List.length_append, encodeLE_length,
        List.length_cons, ih]
      omega

private theorem coefficient_bytes_length {n : Nat}
    (words : Fin n → SmzaRp05ExecutableChallengeStage.FieldWord) :
    (coefficientBytes words).length = n * 8 := by
  simp only [coefficientBytes, encoded_fields_length, List.length_ofFn]

theorem current_final_payload_length (transcript : ReconstructedTranscript) :
    (finalPayload transcript).length = 24904 := by
  simp [finalPayload, coefficient_bytes_length]

theorem current_final_normalized_payload
    (ns : Namespace) (transcript : ReconstructedTranscript) :
    globalNormalizedPayload ns (finalInput transcript) =
      some ⟨.piop, finalPayload transcript⟩ := by
  have normalized := SmzaRp05ExecutableMerkleVerifier.global_nonleaf_frame
    ns .piop (finalPayload transcript) (by decide)
    (current_final_payload_length transcript)
  simpa only [finalInput, V8SmzaOracleParser.roleName] using normalized

theorem current_final_piop_edge
    (ns : Namespace) (transcript : ReconstructedTranscript) :
    globalOnlineNext ns .piop (finalInput transcript) =
      some [(.fpp, transcript.hashFpp)] := by
  unfold globalOnlineNext
  rw [current_final_normalized_payload]
  change some [(V8SmzaOracleParser.Stage.fpp,
    V8SmzaOracleParser.digestAt (finalPayload transcript) 0)] = _
  have digestRead : V8SmzaOracleParser.digestAt (finalPayload transcript) 0 =
      transcript.hashFpp :=
    SmzaRp05ExecutableMerkleVerifier.digest_at_ofFn_append transcript.hashFpp _
  rw [digestRead]

end HegemonCrypto.SmallWood.SmzaRp05CurrentPiopFrameReadback
