#!/usr/bin/env python3

from __future__ import annotations

from math import log10
from pathlib import Path
from typing import Iterable
from xml.sax.saxutils import escape


DEEP_MIDNIGHT = "#0E1C36"
IONOSPHERE = "#1BE7FF"
MOLTEN_AMBER = "#F5A623"
GUARD_RAIL = "#FF4E4E"
PROOF_GREEN = "#19B37E"
SURFACE = "#F4F7FB"
GRID = "#E1E6EE"
TEXT_MUTED = "#5F6B7A"
WHITE = "#FFFFFF"


ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "docs" / "assets"


PACKING_TXS = [1, 2, 4, 8, 16, 32, 64]
PACKING_ONCHAIN = {
    "1 TPS": [56.32, 28.18, 14.11, 7.07, 3.56, 1.80, 0.92],
    "10 TPS": [563.16, 281.77, 141.07, 70.72, 35.55, 17.96, 9.17],
    "100 TPS": [5631.61, 2817.69, 1410.73, 707.25, 355.51, 179.64, 91.70],
}
PACKING_RAW_DA = {
    "1 TPS": 0.35,
    "10 TPS": 3.46,
    "100 TPS": 34.55,
}

INTERVALS = ["1s", "5s", "10s", "30s"]
INTERVAL_PACKING = [2, 8, 16, 64]
INTERVAL_PROOF = [56.28, 11.26, 5.63, 1.88]
INTERVAL_BODY = [0.08, 0.06, 0.06, 0.08]
INTERVAL_DA = [0.69, 0.55, 0.55, 0.74]
INTERVAL_TOTAL = [57.04, 11.87, 6.24, 2.69]


def fmt(value: float) -> str:
    return f"{value:.2f}".rstrip("0").rstrip(".")


def svg_document(width: int, height: int, title: str, desc: str, body: Iterable[str]) -> str:
    return "\n".join(
        [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-labelledby="title desc">',
            f"  <title>{escape(title)}</title>",
            f"  <desc>{escape(desc)}</desc>",
            "  <defs>",
            '    <filter id="softShadow" x="-20%" y="-20%" width="140%" height="140%">',
            '      <feDropShadow dx="0" dy="10" stdDeviation="12" flood-color="#0E1C36" flood-opacity="0.08"/>',
            "    </filter>",
            "  </defs>",
            '  <rect width="100%" height="100%" fill="#FFFFFF"/>',
            *body,
            "</svg>",
        ]
    )


def text(x: float, y: float, value: str, size: int = 16, fill: str = DEEP_MIDNIGHT, weight: int = 400,
         anchor: str = "start", family: str = "'Space Grotesk', Inter, sans-serif", extra: str = "") -> str:
    return (
        f'  <text x="{x:.1f}" y="{y:.1f}" fill="{fill}" font-family="{family}" '
        f'font-size="{size}" font-weight="{weight}" text-anchor="{anchor}" {extra}>{escape(value)}</text>'
    )


def mono_text(x: float, y: float, value: str, size: int = 14, fill: str = TEXT_MUTED,
              anchor: str = "start", extra: str = "") -> str:
    return text(
        x,
        y,
        value,
        size=size,
        fill=fill,
        family="'JetBrains Mono', ui-monospace, monospace",
        anchor=anchor,
        extra=extra,
    )


def polyline(points: list[tuple[float, float]], stroke: str, width: int = 4, dash: str | None = None) -> str:
    points_attr = " ".join(f"{x:.1f},{y:.1f}" for x, y in points)
    dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
    return (
        f'  <polyline points="{points_attr}" fill="none" stroke="{stroke}" stroke-width="{width}" '
        f'stroke-linejoin="round" stroke-linecap="round"{dash_attr}/>'
    )


def circle(x: float, y: float, radius: int, fill: str) -> str:
    return f'  <circle cx="{x:.1f}" cy="{y:.1f}" r="{radius}" fill="{fill}" stroke="#FFFFFF" stroke-width="2"/>'


def rect(x: float, y: float, width: float, height: float, fill: str, stroke: str | None = None,
         radius: int = 24, extra: str = "") -> str:
    stroke_attr = f' stroke="{stroke}" stroke-width="1.5"' if stroke else ""
    return (
        f'  <rect x="{x:.1f}" y="{y:.1f}" width="{width:.1f}" height="{height:.1f}" rx="{radius}" '
        f'fill="{fill}"{stroke_attr} {extra}/>'
    )


def line(x1: float, y1: float, x2: float, y2: float, stroke: str = GRID, width: int = 1, dash: str | None = None) -> str:
    dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
    return (
        f'  <line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" '
        f'stroke="{stroke}" stroke-width="{width}"{dash_attr}/>'
    )


def render_packing_chart() -> None:
    width, height = 1600, 980
    card_x, card_y, card_w, card_h = 56, 48, 1488, 884
    plot_x, plot_y, plot_w, plot_h = 150, 260, 1180, 470

    y_min, y_max = 0.8, 7000.0
    y_ticks = [1, 5, 10, 50, 100, 500, 1000, 5000]
    series_colors = {
        "1 TPS": IONOSPHERE,
        "10 TPS": MOLTEN_AMBER,
        "100 TPS": GUARD_RAIL,
    }

    def map_x(index: int) -> float:
        if len(PACKING_TXS) == 1:
            return plot_x + plot_w / 2
        return plot_x + index * (plot_w / (len(PACKING_TXS) - 1))

    def map_y(value: float) -> float:
        ratio = (log10(value) - log10(y_min)) / (log10(y_max) - log10(y_min))
        return plot_y + plot_h - ratio * plot_h

    body: list[str] = [
        f"<!-- Generated by scripts/render_scalability_plots.py -->",
        rect(card_x, card_y, card_w, card_h, SURFACE, extra='filter="url(#softShadow)"'),
        text(112, 112, "Shipped Lane On-Chain Growth vs. Block Packing", size=34, weight=600),
        text(
            112,
            148,
            "RecursiveBlockV1 = 699,404 B. Shallow packing makes chain growth proof-bound.",
            size=18,
            fill=TEXT_MUTED,
        ),
        text(
            112,
            178,
            "Packing 32-64 shielded tx per non-empty shielded block changes the slope materially.",
            size=18,
            fill=TEXT_MUTED,
        ),
        mono_text(112, 208, "Y axis: GiB/day, logarithmic scale. X axis: average shielded tx per non-empty shielded block."),
    ]

    for tick in y_ticks:
        y = map_y(tick)
        body.append(line(plot_x, y, plot_x + plot_w, y, stroke=GRID, width=1))
        body.append(mono_text(plot_x - 18, y + 5, f"{tick:g}", anchor="end"))

    x_axis_y = plot_y + plot_h
    body.append(line(plot_x, plot_y, plot_x, x_axis_y, stroke=DEEP_MIDNIGHT, width=2))
    body.append(line(plot_x, x_axis_y, plot_x + plot_w, x_axis_y, stroke=DEEP_MIDNIGHT, width=2))

    for idx, txs in enumerate(PACKING_TXS):
        x = map_x(idx)
        body.append(line(x, x_axis_y, x, x_axis_y + 8, stroke=DEEP_MIDNIGHT, width=2))
        body.append(mono_text(x, x_axis_y + 32, str(txs), anchor="middle"))

    body.append(text(plot_x - 112, plot_y + plot_h / 2, "GiB/day", size=18, weight=500,
                     anchor="middle", extra='transform="rotate(-90 58 490)"'))
    body.append(text(plot_x + plot_w / 2, x_axis_y + 74, "average shielded tx per non-empty block", size=18, weight=500, anchor="middle"))

    for label, values in PACKING_ONCHAIN.items():
        points = [(map_x(idx), map_y(value)) for idx, value in enumerate(values)]
        body.append(polyline(points, series_colors[label], width=5))
        for x, y in points:
            body.append(circle(x, y, 6, series_colors[label]))

    legend_x, legend_y, legend_w, legend_h = 1045, 92, 360, 108
    body.append(rect(legend_x, legend_y, legend_w, legend_h, WHITE, stroke=GRID, radius=18))
    legend_items = [
        ("1 TPS on-chain", IONOSPHERE),
        ("10 TPS on-chain", MOLTEN_AMBER),
        ("100 TPS on-chain", GUARD_RAIL),
    ]
    for idx, (label, color) in enumerate(legend_items):
        y = legend_y + 28 + idx * 26
        body.append(line(legend_x + 22, y, legend_x + 48, y, stroke=color, width=5))
        body.append(circle(legend_x + 35, y, 5, color))
        body.append(text(legend_x + 62, y + 6, label, size=16))

    callout_x, callout_y, callout_w, callout_h = 1010, 780, 420, 116
    body.extend(
        [
            rect(callout_x, callout_y, callout_w, callout_h, WHITE, stroke=GRID, radius=18),
            text(callout_x + 24, callout_y + 34, "Raw DA does not improve with packing", size=20, weight=600),
            mono_text(callout_x + 24, callout_y + 64, "1 TPS   = 0.35 GiB/day", fill=IONOSPHERE),
            mono_text(callout_x + 24, callout_y + 88, "10 TPS  = 3.46 GiB/day", fill=MOLTEN_AMBER),
            mono_text(callout_x + 218, callout_y + 64, "100 TPS = 34.55 GiB/day", fill=GUARD_RAIL),
            mono_text(callout_x + 24, callout_y + 106, "Use packing to amortize the recursive proof, not to hide DA cost.", fill=TEXT_MUTED, size=13),
        ]
    )

    desc = (
        "Line chart of on-chain growth on the shipped RecursiveBlockV1 lane as average shielded tx per block rises "
        "from 1 to 64. The y-axis uses a logarithmic scale. Three series show 1 TPS, 10 TPS, and 100 TPS."
    )
    svg = svg_document(width, height, "Shipped lane on-chain growth vs block packing", desc, body)
    (ASSETS / "scalability-block-packing-onchain.svg").write_text(svg, encoding="utf-8")


def render_interval_chart() -> None:
    width, height = 1600, 980
    card_x, card_y, card_w, card_h = 56, 48, 1488, 884
    plot_x, plot_y, plot_w, plot_h = 160, 250, 1220, 400
    max_total = 60.0
    y_ticks = [0, 10, 20, 30, 40, 50, 60]

    def map_x(index: int) -> float:
        slot_w = plot_w / len(INTERVALS)
        return plot_x + slot_w * index + slot_w / 2

    def map_y(value: float) -> float:
        ratio = value / max_total
        return plot_y + plot_h - ratio * plot_h

    body: list[str] = [
        f"<!-- Generated by scripts/render_scalability_plots.py -->",
        rect(card_x, card_y, card_w, card_h, SURFACE, extra='filter="url(#softShadow)"'),
        text(112, 112, "Block-Interval Planning Model", size=34, weight=600),
        text(
            112,
            148,
            "Proof cost dominates until block intervals are long enough to carry meaningful shielded packing.",
            size=18,
            fill=TEXT_MUTED,
        ),
        text(
            112,
            178,
            "This view keeps recursive proof, public tx body, and raw DA separated.",
            size=18,
            fill=TEXT_MUTED,
        ),
        mono_text(
            112,
            208,
            "Assumed packing: 1s->2 tx, 5s->8 tx, 10s->16 tx, 30s->64 tx. Values are projected GiB/day on the shipped lane.",
        ),
        mono_text(
            112,
            232,
            "At this scale the public tx body is visually negligible; the amber cap is the DA component.",
        ),
    ]

    for tick in y_ticks:
        y = map_y(tick)
        body.append(line(plot_x, y, plot_x + plot_w, y, stroke=GRID, width=1))
        body.append(mono_text(plot_x - 16, y + 5, str(tick), anchor="end"))

    x_axis_y = plot_y + plot_h
    body.append(line(plot_x, plot_y, plot_x, x_axis_y, stroke=DEEP_MIDNIGHT, width=2))
    body.append(line(plot_x, x_axis_y, plot_x + plot_w, x_axis_y, stroke=DEEP_MIDNIGHT, width=2))
    body.append(text(plot_x - 110, plot_y + plot_h / 2, "GiB/day", size=18, weight=500,
                     anchor="middle", extra='transform="rotate(-90 50 500)"'))

    slot_w = plot_w / len(INTERVALS)
    bar_w = slot_w * 0.42
    for idx, interval in enumerate(INTERVALS):
        x = map_x(idx)
        proof = INTERVAL_PROOF[idx]
        body_component = INTERVAL_BODY[idx]
        da = INTERVAL_DA[idx]

        proof_top = map_y(proof)
        body_top = map_y(proof + body_component)
        total_top = map_y(proof + body_component + da)

        body.append(rect(x - bar_w / 2, proof_top, bar_w, x_axis_y - proof_top, IONOSPHERE, radius=12))
        body.append(rect(x - bar_w / 2, body_top, bar_w, proof_top - body_top, DEEP_MIDNIGHT, radius=12))
        body.append(rect(x - bar_w / 2, total_top, bar_w, body_top - total_top, MOLTEN_AMBER, radius=12))

        label_w, label_h = 150, 78
        label_y = x_axis_y + 18
        body.append(rect(x - label_w / 2, label_y, label_w, label_h, WHITE, stroke=GRID, radius=14))
        body.append(text(x, label_y + 26, interval, size=18, weight=600, anchor="middle"))
        body.append(mono_text(x, label_y + 50, f"{INTERVAL_PACKING[idx]} tx/block", anchor="middle"))
        body.append(mono_text(x, label_y + 70, f"{fmt(INTERVAL_PACKING[idx] / int(interval[:-1]))} TPS", anchor="middle"))
        body.append(mono_text(x, total_top - 14, f"{fmt(INTERVAL_TOTAL[idx])}", fill=PROOF_GREEN, anchor="middle"))

    legend_x, legend_y, legend_w, legend_h = 1045, 92, 360, 108
    body.append(rect(legend_x, legend_y, legend_w, legend_h, WHITE, stroke=GRID, radius=18))
    legend_items = [
        ("recursive block proof", IONOSPHERE),
        ("public tx body", DEEP_MIDNIGHT),
        ("raw DA ciphertext", MOLTEN_AMBER),
    ]
    for idx, (label, color) in enumerate(legend_items):
        y = legend_y + 28 + idx * 26
        body.append(rect(legend_x + 20, y - 12, 20, 20, color, radius=5))
        body.append(text(legend_x + 54, y + 2, label, size=16))

    footer_x, footer_y, footer_w, footer_h = 100, 816, 1340, 64
    body.extend(
        [
            rect(footer_x, footer_y, footer_w, footer_h, WHITE, stroke=GRID, radius=16),
            text(
                footer_x + 24,
                footer_y + 32,
                "Planning implication",
                size=18,
                weight=600,
            ),
            text(
                footer_x + 24,
                footer_y + 58,
                "Aggressive packing matters. If operators keep tiny shielded blocks, the recursive proof object dominates chain growth.",
                size=17,
                fill=TEXT_MUTED,
            ),
        ]
    )

    desc = (
        "Stacked bar chart of projected daily growth on the shipped RecursiveBlockV1 lane at target block times "
        "of 1, 5, 10, and 30 seconds. Each bar is split into recursive proof bytes, public tx body bytes, and raw DA bytes."
    )
    svg = svg_document(width, height, "Block interval planning model", desc, body)
    (ASSETS / "scalability-block-interval-model.svg").write_text(svg, encoding="utf-8")


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    render_packing_chart()
    render_interval_chart()


if __name__ == "__main__":
    main()
